// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilPlus from "@iconscout/react-unicons/icons/uil-0-plus";

var Impl = {};

function _0Plus(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilPlus, tmp);
}

var make = _0Plus;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
