// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilReact from "@iconscout/react-unicons/icons/uil-react";

var Impl = {};

function _React(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilReact, tmp);
}

var make = _React;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
