// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilAccessibleIconAlt from "@iconscout/react-unicons/icons/uil-accessible-icon-alt";

var Impl = {};

function AccessibleIconAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilAccessibleIconAlt, tmp);
}

var make = AccessibleIconAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
