// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilAdjust from "@iconscout/react-unicons/icons/uil-adjust";

var Impl = {};

function Adjust(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilAdjust, tmp);
}

var make = Adjust;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
