// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilAlignCenterAlt from "@iconscout/react-unicons/icons/uil-align-center-alt";

var Impl = {};

function AlignCenterAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilAlignCenterAlt, tmp);
}

var make = AlignCenterAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
