// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilAlignCenterH from "@iconscout/react-unicons/icons/uil-align-center-h";

var Impl = {};

function AlignCenterH(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilAlignCenterH, tmp);
}

var make = AlignCenterH;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
