// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilAnchor from "@iconscout/react-unicons/icons/uil-anchor";

var Impl = {};

function Anchor(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilAnchor, tmp);
}

var make = Anchor;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
