// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilAndroid from "@iconscout/react-unicons/icons/uil-android";

var Impl = {};

function Android(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilAndroid, tmp);
}

var make = Android;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
