// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilAngleDoubleDown from "@iconscout/react-unicons/icons/uil-angle-double-down";

var Impl = {};

function AngleDoubleDown(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilAngleDoubleDown, tmp);
}

var make = React.memo(AngleDoubleDown);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
