// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilAngleLeft from "@iconscout/react-unicons/icons/uil-angle-left";

var Impl = {};

function AngleLeft(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilAngleLeft, tmp);
}

var make = React.memo(AngleLeft);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
