// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilAngleDoubleRight from "@iconscout/react-unicons/icons/uil-angle-double-right";

var Impl = {};

function AngleDoubleRight(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilAngleDoubleRight, tmp);
}

var make = AngleDoubleRight;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
