// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilAngleRightB from "@iconscout/react-unicons/icons/uil-angle-right-b";

var Impl = {};

function AngleRightB(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilAngleRightB, tmp);
}

var make = React.memo(AngleRightB);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
