// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilAngleLeftB from "@iconscout/react-unicons/icons/uil-angle-left-b";

var Impl = {};

function AngleLeftB(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilAngleLeftB, tmp);
}

var make = React.memo(AngleLeftB);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
