// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilAngleDoubleLeft from "@iconscout/react-unicons/icons/uil-angle-double-left";

var Impl = {};

function AngleDoubleLeft(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilAngleDoubleLeft, tmp);
}

var make = AngleDoubleLeft;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
