// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilAppleAlt from "@iconscout/react-unicons/icons/uil-apple-alt";

var Impl = {};

function AppleAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilAppleAlt, tmp);
}

var make = AppleAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
