// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilArchway from "@iconscout/react-unicons/icons/uil-archway";

var Impl = {};

function Archway(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilArchway, tmp);
}

var make = Archway;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
