// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilArrowsResize from "@iconscout/react-unicons/icons/uil-arrows-resize";

var Impl = {};

function ArrowsResize(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilArrowsResize, tmp);
}

var make = ArrowsResize;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
