// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilArrowsLeftDown from "@iconscout/react-unicons/icons/uil-arrows-left-down";

var Impl = {};

function ArrowsLeftDown(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilArrowsLeftDown, tmp);
}

var make = ArrowsLeftDown;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
