// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilArrowsUpRight from "@iconscout/react-unicons/icons/uil-arrows-up-right";

var Impl = {};

function ArrowsUpRight(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilArrowsUpRight, tmp);
}

var make = ArrowsUpRight;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
