// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilArrowCircleUp from "@iconscout/react-unicons/icons/uil-arrow-circle-up";

var Impl = {};

function ArrowCircleUp(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilArrowCircleUp, tmp);
}

var make = React.memo(ArrowCircleUp);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
