// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilArrowToBottom from "@iconscout/react-unicons/icons/uil-arrow-to-bottom";

var Impl = {};

function ArrowToBottom(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilArrowToBottom, tmp);
}

var make = ArrowToBottom;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
