// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilArrowRight from "@iconscout/react-unicons/icons/uil-arrow-right";

var Impl = {};

function ArrowRight(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilArrowRight, tmp);
}

var make = React.memo(ArrowRight);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
