// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilArrowsH from "@iconscout/react-unicons/icons/uil-arrows-h";

var Impl = {};

function ArrowsH(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilArrowsH, tmp);
}

var make = ArrowsH;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
