// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilArrowCompressH from "@iconscout/react-unicons/icons/uil-arrow-compress-h";

var Impl = {};

function ArrowCompressH(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilArrowCompressH, tmp);
}

var make = ArrowCompressH;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
