// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilArrowsRightDown from "@iconscout/react-unicons/icons/uil-arrows-right-down";

var Impl = {};

function ArrowsRightDown(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilArrowsRightDown, tmp);
}

var make = ArrowsRightDown;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
