// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilArrowToRight from "@iconscout/react-unicons/icons/uil-arrow-to-right";

var Impl = {};

function ArrowToRight(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilArrowToRight, tmp);
}

var make = React.memo(ArrowToRight);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
