// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilAwardAlt from "@iconscout/react-unicons/icons/uil-award-alt";

var Impl = {};

function AwardAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilAwardAlt, tmp);
}

var make = AwardAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
