// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilBagAlt from "@iconscout/react-unicons/icons/uil-bag-alt";

var Impl = {};

function BagAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilBagAlt, tmp);
}

var make = React.memo(BagAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
