// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilBalanceScale from "@iconscout/react-unicons/icons/uil-balance-scale";

var Impl = {};

function BalanceScale(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilBalanceScale, tmp);
}

var make = React.memo(BalanceScale);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
