// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilBars from "@iconscout/react-unicons/icons/uil-bars";

var Impl = {};

function Bars(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilBars, tmp);
}

var make = Bars;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
