// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilBatteryEmpty from "@iconscout/react-unicons/icons/uil-battery-empty";

var Impl = {};

function BatteryEmpty(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilBatteryEmpty, tmp);
}

var make = React.memo(BatteryEmpty);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
