// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilBitcoinCircle from "@iconscout/react-unicons/icons/uil-bitcoin-circle";

var Impl = {};

function BitcoinCircle(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilBitcoinCircle, tmp);
}

var make = BitcoinCircle;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
