// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilBitcoinSign from "@iconscout/react-unicons/icons/uil-bitcoin-sign";

var Impl = {};

function BitcoinSign(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilBitcoinSign, tmp);
}

var make = BitcoinSign;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
