// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilBluetoothB from "@iconscout/react-unicons/icons/uil-bluetooth-b";

var Impl = {};

function BluetoothB(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilBluetoothB, tmp);
}

var make = BluetoothB;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
