// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilBold from "@iconscout/react-unicons/icons/uil-bold";

var Impl = {};

function Bold(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilBold, tmp);
}

var make = Bold;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
