// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilBoltSlash from "@iconscout/react-unicons/icons/uil-bolt-slash";

var Impl = {};

function BoltSlash(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilBoltSlash, tmp);
}

var make = BoltSlash;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
