// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilBookOpen from "@iconscout/react-unicons/icons/uil-book-open";

var Impl = {};

function BookOpen(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilBookOpen, tmp);
}

var make = BookOpen;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
