// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilBookMedical from "@iconscout/react-unicons/icons/uil-book-medical";

var Impl = {};

function BookMedical(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilBookMedical, tmp);
}

var make = BookMedical;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
