// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilBookAlt from "@iconscout/react-unicons/icons/uil-book-alt";

var Impl = {};

function BookAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilBookAlt, tmp);
}

var make = BookAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
