// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilBookmarkFull from "@iconscout/react-unicons/icons/uil-bookmark-full";

var Impl = {};

function BookmarkFull(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilBookmarkFull, tmp);
}

var make = BookmarkFull;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
