// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilBookmark from "@iconscout/react-unicons/icons/uil-bookmark";

var Impl = {};

function Bookmark(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilBookmark, tmp);
}

var make = Bookmark;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
