// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilBorderRight from "@iconscout/react-unicons/icons/uil-border-right";

var Impl = {};

function BorderRight(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilBorderRight, tmp);
}

var make = BorderRight;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
