// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilBorderOut from "@iconscout/react-unicons/icons/uil-border-out";

var Impl = {};

function BorderOut(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilBorderOut, tmp);
}

var make = BorderOut;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
