// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilBorderBottom from "@iconscout/react-unicons/icons/uil-border-bottom";

var Impl = {};

function BorderBottom(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilBorderBottom, tmp);
}

var make = React.memo(BorderBottom);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
