// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilBowlingBall from "@iconscout/react-unicons/icons/uil-bowling-ball";

var Impl = {};

function BowlingBall(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilBowlingBall, tmp);
}

var make = BowlingBall;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
