// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilBrain from "@iconscout/react-unicons/icons/uil-brain";

var Impl = {};

function Brain(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilBrain, tmp);
}

var make = React.memo(Brain);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
