// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilBrightnessLow from "@iconscout/react-unicons/icons/uil-brightness-low";

var Impl = {};

function BrightnessLow(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilBrightnessLow, tmp);
}

var make = BrightnessLow;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
