// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilBrightnessPlus from "@iconscout/react-unicons/icons/uil-brightness-plus";

var Impl = {};

function BrightnessPlus(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilBrightnessPlus, tmp);
}

var make = React.memo(BrightnessPlus);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
