// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilBrowser from "@iconscout/react-unicons/icons/uil-browser";

var Impl = {};

function Browser(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilBrowser, tmp);
}

var make = Browser;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
