// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilBusAlt from "@iconscout/react-unicons/icons/uil-bus-alt";

var Impl = {};

function BusAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilBusAlt, tmp);
}

var make = BusAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
