// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCancel from "@iconscout/react-unicons/icons/uil-cancel";

var Impl = {};

function Cancel(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCancel, tmp);
}

var make = React.memo(Cancel);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
