// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCarWash from "@iconscout/react-unicons/icons/uil-car-wash";

var Impl = {};

function CarWash(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCarWash, tmp);
}

var make = React.memo(CarWash);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
