// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilChartBarAlt from "@iconscout/react-unicons/icons/uil-chart-bar-alt";

var Impl = {};

function ChartBarAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilChartBarAlt, tmp);
}

var make = React.memo(ChartBarAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
