// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilChatInfo from "@iconscout/react-unicons/icons/uil-chat-info";

var Impl = {};

function ChatInfo(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilChatInfo, tmp);
}

var make = ChatInfo;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
