// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilClipboardNotes from "@iconscout/react-unicons/icons/uil-clipboard-notes";

var Impl = {};

function ClipboardNotes(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilClipboardNotes, tmp);
}

var make = React.memo(ClipboardNotes);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
