// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilClipboard from "@iconscout/react-unicons/icons/uil-clipboard";

var Impl = {};

function Clipboard(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilClipboard, tmp);
}

var make = Clipboard;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
