// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilClockThree from "@iconscout/react-unicons/icons/uil-clock-three";

var Impl = {};

function ClockThree(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilClockThree, tmp);
}

var make = ClockThree;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
