// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilClockTen from "@iconscout/react-unicons/icons/uil-clock-ten";

var Impl = {};

function ClockTen(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilClockTen, tmp);
}

var make = ClockTen;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
