// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCloudExclamation from "@iconscout/react-unicons/icons/uil-cloud-exclamation";

var Impl = {};

function CloudExclamation(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCloudExclamation, tmp);
}

var make = CloudExclamation;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
