// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCloudComputing from "@iconscout/react-unicons/icons/uil-cloud-computing";

var Impl = {};

function CloudComputing(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCloudComputing, tmp);
}

var make = React.memo(CloudComputing);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
