// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCloudSunMeatball from "@iconscout/react-unicons/icons/uil-cloud-sun-meatball";

var Impl = {};

function CloudSunMeatball(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCloudSunMeatball, tmp);
}

var make = React.memo(CloudSunMeatball);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
