// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCloudDrizzle from "@iconscout/react-unicons/icons/uil-cloud-drizzle";

var Impl = {};

function CloudDrizzle(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCloudDrizzle, tmp);
}

var make = CloudDrizzle;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
