// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCloudMoonShowers from "@iconscout/react-unicons/icons/uil-cloud-moon-showers";

var Impl = {};

function CloudMoonShowers(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCloudMoonShowers, tmp);
}

var make = React.memo(CloudMoonShowers);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
