// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCloudSunRainAlt from "@iconscout/react-unicons/icons/uil-cloud-sun-rain-alt";

var Impl = {};

function CloudSunRainAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCloudSunRainAlt, tmp);
}

var make = React.memo(CloudSunRainAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
