// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCloudMoonMeatball from "@iconscout/react-unicons/icons/uil-cloud-moon-meatball";

var Impl = {};

function CloudMoonMeatball(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCloudMoonMeatball, tmp);
}

var make = CloudMoonMeatball;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
