// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCloudShowers from "@iconscout/react-unicons/icons/uil-cloud-showers";

var Impl = {};

function CloudShowers(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCloudShowers, tmp);
}

var make = CloudShowers;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
