// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCloudMoon from "@iconscout/react-unicons/icons/uil-cloud-moon";

var Impl = {};

function CloudMoon(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCloudMoon, tmp);
}

var make = CloudMoon;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
