// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCloudDataConnection from "@iconscout/react-unicons/icons/uil-cloud-data-connection";

var Impl = {};

function CloudDataConnection(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCloudDataConnection, tmp);
}

var make = CloudDataConnection;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
