// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCloudTimes from "@iconscout/react-unicons/icons/uil-cloud-times";

var Impl = {};

function CloudTimes(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCloudTimes, tmp);
}

var make = CloudTimes;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
