// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCloudSun from "@iconscout/react-unicons/icons/uil-cloud-sun";

var Impl = {};

function CloudSun(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCloudSun, tmp);
}

var make = CloudSun;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
