// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCloudSunTear from "@iconscout/react-unicons/icons/uil-cloud-sun-tear";

var Impl = {};

function CloudSunTear(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCloudSunTear, tmp);
}

var make = React.memo(CloudSunTear);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
