// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCloudSunRain from "@iconscout/react-unicons/icons/uil-cloud-sun-rain";

var Impl = {};

function CloudSunRain(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCloudSunRain, tmp);
}

var make = CloudSunRain;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
