// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCloudShowersHeavy from "@iconscout/react-unicons/icons/uil-cloud-showers-heavy";

var Impl = {};

function CloudShowersHeavy(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCloudShowersHeavy, tmp);
}

var make = React.memo(CloudShowersHeavy);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
