// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCog from "@iconscout/react-unicons/icons/uil-cog";

var Impl = {};

function Cog(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCog, tmp);
}

var make = Cog;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
