// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCommentQuestion from "@iconscout/react-unicons/icons/uil-comment-question";

var Impl = {};

function CommentQuestion(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCommentQuestion, tmp);
}

var make = CommentQuestion;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
