// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCommentImage from "@iconscout/react-unicons/icons/uil-comment-image";

var Impl = {};

function CommentImage(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCommentImage, tmp);
}

var make = CommentImage;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
