// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilComments from "@iconscout/react-unicons/icons/uil-comments";

var Impl = {};

function Comments(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilComments, tmp);
}

var make = Comments;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
