// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCommentAltEdit from "@iconscout/react-unicons/icons/uil-comment-alt-edit";

var Impl = {};

function CommentAltEdit(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCommentAltEdit, tmp);
}

var make = CommentAltEdit;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
