// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCommentAltDownload from "@iconscout/react-unicons/icons/uil-comment-alt-download";

var Impl = {};

function CommentAltDownload(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCommentAltDownload, tmp);
}

var make = CommentAltDownload;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
