// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCommentHeart from "@iconscout/react-unicons/icons/uil-comment-heart";

var Impl = {};

function CommentHeart(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCommentHeart, tmp);
}

var make = CommentHeart;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
