// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCommentAltSearch from "@iconscout/react-unicons/icons/uil-comment-alt-search";

var Impl = {};

function CommentAltSearch(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCommentAltSearch, tmp);
}

var make = CommentAltSearch;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
