// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCommentAltHeart from "@iconscout/react-unicons/icons/uil-comment-alt-heart";

var Impl = {};

function CommentAltHeart(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCommentAltHeart, tmp);
}

var make = CommentAltHeart;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
