// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCommentAltRedo from "@iconscout/react-unicons/icons/uil-comment-alt-redo";

var Impl = {};

function CommentAltRedo(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCommentAltRedo, tmp);
}

var make = React.memo(CommentAltRedo);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
