// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCommentAltLines from "@iconscout/react-unicons/icons/uil-comment-alt-lines";

var Impl = {};

function CommentAltLines(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCommentAltLines, tmp);
}

var make = CommentAltLines;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
