// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCompressPoint from "@iconscout/react-unicons/icons/uil-compress-point";

var Impl = {};

function CompressPoint(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCompressPoint, tmp);
}

var make = CompressPoint;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
