// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCompressV from "@iconscout/react-unicons/icons/uil-compress-v";

var Impl = {};

function CompressV(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCompressV, tmp);
}

var make = CompressV;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
