// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCopyright from "@iconscout/react-unicons/icons/uil-copyright";

var Impl = {};

function Copyright(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCopyright, tmp);
}

var make = Copyright;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
