// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCornerUpRightAlt from "@iconscout/react-unicons/icons/uil-corner-up-right-alt";

var Impl = {};

function CornerUpRightAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCornerUpRightAlt, tmp);
}

var make = React.memo(CornerUpRightAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
