// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCornerLeftDown from "@iconscout/react-unicons/icons/uil-corner-left-down";

var Impl = {};

function CornerLeftDown(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCornerLeftDown, tmp);
}

var make = CornerLeftDown;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
