// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCornerRightDown from "@iconscout/react-unicons/icons/uil-corner-right-down";

var Impl = {};

function CornerRightDown(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCornerRightDown, tmp);
}

var make = CornerRightDown;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
