// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCornerDownRightAlt from "@iconscout/react-unicons/icons/uil-corner-down-right-alt";

var Impl = {};

function CornerDownRightAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCornerDownRightAlt, tmp);
}

var make = React.memo(CornerDownRightAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
