// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCornerUpLeftAlt from "@iconscout/react-unicons/icons/uil-corner-up-left-alt";

var Impl = {};

function CornerUpLeftAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCornerUpLeftAlt, tmp);
}

var make = CornerUpLeftAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
