// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCreateDashboard from "@iconscout/react-unicons/icons/uil-create-dashboard";

var Impl = {};

function CreateDashboard(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCreateDashboard, tmp);
}

var make = React.memo(CreateDashboard);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
