// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCreativeCommonsPd from "@iconscout/react-unicons/icons/uil-creative-commons-pd";

var Impl = {};

function CreativeCommonsPd(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCreativeCommonsPd, tmp);
}

var make = React.memo(CreativeCommonsPd);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
