// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCreditCard from "@iconscout/react-unicons/icons/uil-credit-card";

var Impl = {};

function CreditCard(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCreditCard, tmp);
}

var make = React.memo(CreditCard);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
