// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCreditCardSearch from "@iconscout/react-unicons/icons/uil-credit-card-search";

var Impl = {};

function CreditCardSearch(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCreditCardSearch, tmp);
}

var make = React.memo(CreditCardSearch);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
