// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCropAlt from "@iconscout/react-unicons/icons/uil-crop-alt";

var Impl = {};

function CropAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCropAlt, tmp);
}

var make = CropAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
