// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCrosshairAlt from "@iconscout/react-unicons/icons/uil-crosshair-alt";

var Impl = {};

function CrosshairAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCrosshairAlt, tmp);
}

var make = React.memo(CrosshairAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
