// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCss3Simple from "@iconscout/react-unicons/icons/uil-css3-simple";

var Impl = {};

function Css3Simple(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCss3Simple, tmp);
}

var make = React.memo(Css3Simple);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
