// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilCube from "@iconscout/react-unicons/icons/uil-cube";

var Impl = {};

function Cube(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilCube, tmp);
}

var make = Cube;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
