// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilDesktopCloudAlt from "@iconscout/react-unicons/icons/uil-desktop-cloud-alt";

var Impl = {};

function DesktopCloudAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilDesktopCloudAlt, tmp);
}

var make = DesktopCloudAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
