// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilDesktopAlt from "@iconscout/react-unicons/icons/uil-desktop-alt";

var Impl = {};

function DesktopAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilDesktopAlt, tmp);
}

var make = DesktopAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
