// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilDialpadAlt from "@iconscout/react-unicons/icons/uil-dialpad-alt";

var Impl = {};

function DialpadAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilDialpadAlt, tmp);
}

var make = React.memo(DialpadAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
