// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilDialpad from "@iconscout/react-unicons/icons/uil-dialpad";

var Impl = {};

function Dialpad(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilDialpad, tmp);
}

var make = Dialpad;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
