// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilDirections from "@iconscout/react-unicons/icons/uil-directions";

var Impl = {};

function Directions(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilDirections, tmp);
}

var make = React.memo(Directions);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
