// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilDocumentLayoutRight from "@iconscout/react-unicons/icons/uil-document-layout-right";

var Impl = {};

function DocumentLayoutRight(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilDocumentLayoutRight, tmp);
}

var make = DocumentLayoutRight;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
