// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilDocumentLayoutCenter from "@iconscout/react-unicons/icons/uil-document-layout-center";

var Impl = {};

function DocumentLayoutCenter(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilDocumentLayoutCenter, tmp);
}

var make = DocumentLayoutCenter;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
