// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilDrill from "@iconscout/react-unicons/icons/uil-drill";

var Impl = {};

function Drill(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilDrill, tmp);
}

var make = Drill;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
