// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilElipsisDoubleVAlt from "@iconscout/react-unicons/icons/uil-elipsis-double-v-alt";

var Impl = {};

function ElipsisDoubleVAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilElipsisDoubleVAlt, tmp);
}

var make = React.memo(ElipsisDoubleVAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
