// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilEnvelopeMinus from "@iconscout/react-unicons/icons/uil-envelope-minus";

var Impl = {};

function EnvelopeMinus(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilEnvelopeMinus, tmp);
}

var make = EnvelopeMinus;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
