// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilEnvelopeShare from "@iconscout/react-unicons/icons/uil-envelope-share";

var Impl = {};

function EnvelopeShare(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilEnvelopeShare, tmp);
}

var make = React.memo(EnvelopeShare);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
