// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilEnvelopeReceive from "@iconscout/react-unicons/icons/uil-envelope-receive";

var Impl = {};

function EnvelopeReceive(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilEnvelopeReceive, tmp);
}

var make = EnvelopeReceive;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
