// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilEnvelopeDownloadAlt from "@iconscout/react-unicons/icons/uil-envelope-download-alt";

var Impl = {};

function EnvelopeDownloadAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilEnvelopeDownloadAlt, tmp);
}

var make = EnvelopeDownloadAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
