// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilEnvelopeSearch from "@iconscout/react-unicons/icons/uil-envelope-search";

var Impl = {};

function EnvelopeSearch(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilEnvelopeSearch, tmp);
}

var make = React.memo(EnvelopeSearch);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
