// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilEnvelopeExclamation from "@iconscout/react-unicons/icons/uil-envelope-exclamation";

var Impl = {};

function EnvelopeExclamation(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilEnvelopeExclamation, tmp);
}

var make = React.memo(EnvelopeExclamation);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
