// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilEnvelopeAdd from "@iconscout/react-unicons/icons/uil-envelope-add";

var Impl = {};

function EnvelopeAdd(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilEnvelopeAdd, tmp);
}

var make = EnvelopeAdd;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
