// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilEstate from "@iconscout/react-unicons/icons/uil-estate";

var Impl = {};

function Estate(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilEstate, tmp);
}

var make = Estate;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
