// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilExchange from "@iconscout/react-unicons/icons/uil-exchange";

var Impl = {};

function Exchange(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilExchange, tmp);
}

var make = Exchange;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
