// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilExpandRight from "@iconscout/react-unicons/icons/uil-expand-right";

var Impl = {};

function ExpandRight(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilExpandRight, tmp);
}

var make = ExpandRight;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
