// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilExpandFromCorner from "@iconscout/react-unicons/icons/uil-expand-from-corner";

var Impl = {};

function ExpandFromCorner(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilExpandFromCorner, tmp);
}

var make = React.memo(ExpandFromCorner);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
