// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilExpandArrows from "@iconscout/react-unicons/icons/uil-expand-arrows";

var Impl = {};

function ExpandArrows(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilExpandArrows, tmp);
}

var make = ExpandArrows;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
