// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilExposureIncrease from "@iconscout/react-unicons/icons/uil-exposure-increase";

var Impl = {};

function ExposureIncrease(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilExposureIncrease, tmp);
}

var make = React.memo(ExposureIncrease);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
