// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilFacebook from "@iconscout/react-unicons/icons/uil-facebook";

var Impl = {};

function Facebook(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilFacebook, tmp);
}

var make = Facebook;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
