// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilFacebookF from "@iconscout/react-unicons/icons/uil-facebook-f";

var Impl = {};

function FacebookF(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilFacebookF, tmp);
}

var make = React.memo(FacebookF);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
