// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilFacebookMessengerAlt from "@iconscout/react-unicons/icons/uil-facebook-messenger-alt";

var Impl = {};

function FacebookMessengerAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilFacebookMessengerAlt, tmp);
}

var make = FacebookMessengerAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
