// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilFastMail from "@iconscout/react-unicons/icons/uil-fast-mail";

var Impl = {};

function FastMail(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilFastMail, tmp);
}

var make = FastMail;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
