// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilFileUpload from "@iconscout/react-unicons/icons/uil-file-upload";

var Impl = {};

function FileUpload(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilFileUpload, tmp);
}

var make = FileUpload;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
