// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilFileExclamationAlt from "@iconscout/react-unicons/icons/uil-file-exclamation-alt";

var Impl = {};

function FileExclamationAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilFileExclamationAlt, tmp);
}

var make = React.memo(FileExclamationAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
