// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilFilePlusAlt from "@iconscout/react-unicons/icons/uil-file-plus-alt";

var Impl = {};

function FilePlusAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilFilePlusAlt, tmp);
}

var make = React.memo(FilePlusAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
