// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilFileShieldAlt from "@iconscout/react-unicons/icons/uil-file-shield-alt";

var Impl = {};

function FileShieldAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilFileShieldAlt, tmp);
}

var make = React.memo(FileShieldAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
