// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilFileMedical from "@iconscout/react-unicons/icons/uil-file-medical";

var Impl = {};

function FileMedical(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilFileMedical, tmp);
}

var make = FileMedical;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
