// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilFileNetwork from "@iconscout/react-unicons/icons/uil-file-network";

var Impl = {};

function FileNetwork(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilFileNetwork, tmp);
}

var make = React.memo(FileNetwork);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
