// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilFileBookmarkAlt from "@iconscout/react-unicons/icons/uil-file-bookmark-alt";

var Impl = {};

function FileBookmarkAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilFileBookmarkAlt, tmp);
}

var make = React.memo(FileBookmarkAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
