// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilFileTimesAlt from "@iconscout/react-unicons/icons/uil-file-times-alt";

var Impl = {};

function FileTimesAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilFileTimesAlt, tmp);
}

var make = React.memo(FileTimesAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
