// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilFileTimes from "@iconscout/react-unicons/icons/uil-file-times";

var Impl = {};

function FileTimes(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilFileTimes, tmp);
}

var make = FileTimes;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
