// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilFileContract from "@iconscout/react-unicons/icons/uil-file-contract";

var Impl = {};

function FileContract(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilFileContract, tmp);
}

var make = FileContract;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
