// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilFlipV from "@iconscout/react-unicons/icons/uil-flip-v";

var Impl = {};

function FlipV(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilFlipV, tmp);
}

var make = FlipV;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
