// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilFolderPlus from "@iconscout/react-unicons/icons/uil-folder-plus";

var Impl = {};

function FolderPlus(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilFolderPlus, tmp);
}

var make = React.memo(FolderPlus);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
