// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilFolderCheck from "@iconscout/react-unicons/icons/uil-folder-check";

var Impl = {};

function FolderCheck(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilFolderCheck, tmp);
}

var make = FolderCheck;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
