// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilFolderOpen from "@iconscout/react-unicons/icons/uil-folder-open";

var Impl = {};

function FolderOpen(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilFolderOpen, tmp);
}

var make = React.memo(FolderOpen);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
