// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilFolderDownload from "@iconscout/react-unicons/icons/uil-folder-download";

var Impl = {};

function FolderDownload(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilFolderDownload, tmp);
}

var make = React.memo(FolderDownload);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
