// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilForecastcloudMoonTear from "@iconscout/react-unicons/icons/uil-forecastcloud-moon-tear";

var Impl = {};

function ForecastcloudMoonTear(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilForecastcloudMoonTear, tmp);
}

var make = React.memo(ForecastcloudMoonTear);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
