// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilForwadedCall from "@iconscout/react-unicons/icons/uil-forwaded-call";

var Impl = {};

function ForwadedCall(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilForwadedCall, tmp);
}

var make = ForwadedCall;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
