// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilGithubAlt from "@iconscout/react-unicons/icons/uil-github-alt";

var Impl = {};

function GithubAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilGithubAlt, tmp);
}

var make = React.memo(GithubAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
