// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilGlassMartiniAltSlash from "@iconscout/react-unicons/icons/uil-glass-martini-alt-slash";

var Impl = {};

function GlassMartiniAltSlash(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilGlassMartiniAltSlash, tmp);
}

var make = React.memo(GlassMartiniAltSlash);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
