// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilGolfBall from "@iconscout/react-unicons/icons/uil-golf-ball";

var Impl = {};

function GolfBall(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilGolfBall, tmp);
}

var make = React.memo(GolfBall);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
