// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilGoogleDriveAlt from "@iconscout/react-unicons/icons/uil-google-drive-alt";

var Impl = {};

function GoogleDriveAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilGoogleDriveAlt, tmp);
}

var make = React.memo(GoogleDriveAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
