// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilGrinTongueWink from "@iconscout/react-unicons/icons/uil-grin-tongue-wink";

var Impl = {};

function GrinTongueWink(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilGrinTongueWink, tmp);
}

var make = GrinTongueWink;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
