// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilGrinTongueWinkAlt from "@iconscout/react-unicons/icons/uil-grin-tongue-wink-alt";

var Impl = {};

function GrinTongueWinkAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilGrinTongueWinkAlt, tmp);
}

var make = GrinTongueWinkAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
