// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilGripHorizontalLine from "@iconscout/react-unicons/icons/uil-grip-horizontal-line";

var Impl = {};

function GripHorizontalLine(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilGripHorizontalLine, tmp);
}

var make = GripHorizontalLine;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
