// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilHorizontalDistributionLeft from "@iconscout/react-unicons/icons/uil-horizontal-distribution-left";

var Impl = {};

function HorizontalDistributionLeft(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilHorizontalDistributionLeft, tmp);
}

var make = HorizontalDistributionLeft;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
