// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilHorizontalAlignLeft from "@iconscout/react-unicons/icons/uil-horizontal-align-left";

var Impl = {};

function HorizontalAlignLeft(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilHorizontalAlignLeft, tmp);
}

var make = HorizontalAlignLeft;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
