// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilHospitalSquareSign from "@iconscout/react-unicons/icons/uil-hospital-square-sign";

var Impl = {};

function HospitalSquareSign(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilHospitalSquareSign, tmp);
}

var make = React.memo(HospitalSquareSign);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
