// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilHtml3Alt from "@iconscout/react-unicons/icons/uil-html3-alt";

var Impl = {};

function Html3Alt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilHtml3Alt, tmp);
}

var make = React.memo(Html3Alt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
