// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilHtml5 from "@iconscout/react-unicons/icons/uil-html5";

var Impl = {};

function Html5(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilHtml5, tmp);
}

var make = React.memo(Html5);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
