// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilIcons from "@iconscout/react-unicons/icons/uil-icons";

var Impl = {};

function Icons(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilIcons, tmp);
}

var make = Icons;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
