// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilImageUpload from "@iconscout/react-unicons/icons/uil-image-upload";

var Impl = {};

function ImageUpload(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilImageUpload, tmp);
}

var make = ImageUpload;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
