// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilImageMinus from "@iconscout/react-unicons/icons/uil-image-minus";

var Impl = {};

function ImageMinus(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilImageMinus, tmp);
}

var make = React.memo(ImageMinus);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
