// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilImageResizeSquare from "@iconscout/react-unicons/icons/uil-image-resize-square";

var Impl = {};

function ImageResizeSquare(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilImageResizeSquare, tmp);
}

var make = React.memo(ImageResizeSquare);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
