// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilImageDownload from "@iconscout/react-unicons/icons/uil-image-download";

var Impl = {};

function ImageDownload(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilImageDownload, tmp);
}

var make = ImageDownload;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
