// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilImageRedo from "@iconscout/react-unicons/icons/uil-image-redo";

var Impl = {};

function ImageRedo(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilImageRedo, tmp);
}

var make = ImageRedo;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
