// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilImageResizeLandscape from "@iconscout/react-unicons/icons/uil-image-resize-landscape";

var Impl = {};

function ImageResizeLandscape(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilImageResizeLandscape, tmp);
}

var make = ImageResizeLandscape;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
