// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilIntercomAlt from "@iconscout/react-unicons/icons/uil-intercom-alt";

var Impl = {};

function IntercomAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilIntercomAlt, tmp);
}

var make = React.memo(IntercomAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
