// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilJavaScript from "@iconscout/react-unicons/icons/uil-java-script";

var Impl = {};

function JavaScript(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilJavaScript, tmp);
}

var make = React.memo(JavaScript);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
