// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilKeyboardShow from "@iconscout/react-unicons/icons/uil-keyboard-show";

var Impl = {};

function KeyboardShow(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilKeyboardShow, tmp);
}

var make = KeyboardShow;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
