// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilKeyholeCircle from "@iconscout/react-unicons/icons/uil-keyhole-circle";

var Impl = {};

function KeyholeCircle(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilKeyholeCircle, tmp);
}

var make = React.memo(KeyholeCircle);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
