// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilLabel from "@iconscout/react-unicons/icons/uil-label";

var Impl = {};

function Label(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilLabel, tmp);
}

var make = Label;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
