// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilLayerGroupSlash from "@iconscout/react-unicons/icons/uil-layer-group-slash";

var Impl = {};

function LayerGroupSlash(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilLayerGroupSlash, tmp);
}

var make = LayerGroupSlash;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
