// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilLeftArrowFromLeft from "@iconscout/react-unicons/icons/uil-left-arrow-from-left";

var Impl = {};

function LeftArrowFromLeft(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilLeftArrowFromLeft, tmp);
}

var make = React.memo(LeftArrowFromLeft);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
