// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilLeftArrowToLeft from "@iconscout/react-unicons/icons/uil-left-arrow-to-left";

var Impl = {};

function LeftArrowToLeft(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilLeftArrowToLeft, tmp);
}

var make = React.memo(LeftArrowToLeft);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
