// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilLeftToRightTextDirection from "@iconscout/react-unicons/icons/uil-left-to-right-text-direction";

var Impl = {};

function LeftToRightTextDirection(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilLeftToRightTextDirection, tmp);
}

var make = React.memo(LeftToRightTextDirection);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
