// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilLeftIndent from "@iconscout/react-unicons/icons/uil-left-indent";

var Impl = {};

function LeftIndent(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilLeftIndent, tmp);
}

var make = LeftIndent;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
