// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilLetterChineseA from "@iconscout/react-unicons/icons/uil-letter-chinese-a";

var Impl = {};

function LetterChineseA(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilLetterChineseA, tmp);
}

var make = React.memo(LetterChineseA);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
