// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilLetterHindiA from "@iconscout/react-unicons/icons/uil-letter-hindi-a";

var Impl = {};

function LetterHindiA(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilLetterHindiA, tmp);
}

var make = React.memo(LetterHindiA);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
