// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilLifeRing from "@iconscout/react-unicons/icons/uil-life-ring";

var Impl = {};

function LifeRing(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilLifeRing, tmp);
}

var make = LifeRing;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
