// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilLineSpacing from "@iconscout/react-unicons/icons/uil-line-spacing";

var Impl = {};

function LineSpacing(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilLineSpacing, tmp);
}

var make = LineSpacing;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
