// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilLinkAlt from "@iconscout/react-unicons/icons/uil-link-alt";

var Impl = {};

function LinkAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilLinkAlt, tmp);
}

var make = React.memo(LinkAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
