// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilLinkedinAlt from "@iconscout/react-unicons/icons/uil-linkedin-alt";

var Impl = {};

function LinkedinAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilLinkedinAlt, tmp);
}

var make = LinkedinAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
