// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilLinkAdd from "@iconscout/react-unicons/icons/uil-link-add";

var Impl = {};

function LinkAdd(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilLinkAdd, tmp);
}

var make = LinkAdd;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
