// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilListOlAlt from "@iconscout/react-unicons/icons/uil-list-ol-alt";

var Impl = {};

function ListOlAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilListOlAlt, tmp);
}

var make = ListOlAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
