// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilListUiAlt from "@iconscout/react-unicons/icons/uil-list-ui-alt";

var Impl = {};

function ListUiAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilListUiAlt, tmp);
}

var make = ListUiAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
