// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilLocationPoint from "@iconscout/react-unicons/icons/uil-location-point";

var Impl = {};

function LocationPoint(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilLocationPoint, tmp);
}

var make = React.memo(LocationPoint);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
