// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilLockAlt from "@iconscout/react-unicons/icons/uil-lock-alt";

var Impl = {};

function LockAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilLockAlt, tmp);
}

var make = LockAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
