// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilLockSlash from "@iconscout/react-unicons/icons/uil-lock-slash";

var Impl = {};

function LockSlash(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilLockSlash, tmp);
}

var make = LockSlash;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
