// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilLottiefilesAlt from "@iconscout/react-unicons/icons/uil-lottiefiles-alt";

var Impl = {};

function LottiefilesAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilLottiefilesAlt, tmp);
}

var make = LottiefilesAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
