// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilMapMarkerQuestion from "@iconscout/react-unicons/icons/uil-map-marker-question";

var Impl = {};

function MapMarkerQuestion(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilMapMarkerQuestion, tmp);
}

var make = MapMarkerQuestion;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
