// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilMapMarkerAlt from "@iconscout/react-unicons/icons/uil-map-marker-alt";

var Impl = {};

function MapMarkerAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilMapMarkerAlt, tmp);
}

var make = React.memo(MapMarkerAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
