// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilMapMarkerEdit from "@iconscout/react-unicons/icons/uil-map-marker-edit";

var Impl = {};

function MapMarkerEdit(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilMapMarkerEdit, tmp);
}

var make = MapMarkerEdit;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
