// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilMapMarkerShield from "@iconscout/react-unicons/icons/uil-map-marker-shield";

var Impl = {};

function MapMarkerShield(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilMapMarkerShield, tmp);
}

var make = React.memo(MapMarkerShield);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
