// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilMapPinAlt from "@iconscout/react-unicons/icons/uil-map-pin-alt";

var Impl = {};

function MapPinAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilMapPinAlt, tmp);
}

var make = React.memo(MapPinAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
