// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilMasterCard from "@iconscout/react-unicons/icons/uil-master-card";

var Impl = {};

function MasterCard(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilMasterCard, tmp);
}

var make = MasterCard;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
