// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilMaximizeLeft from "@iconscout/react-unicons/icons/uil-maximize-left";

var Impl = {};

function MaximizeLeft(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilMaximizeLeft, tmp);
}

var make = MaximizeLeft;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
