// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilMedicalDrip from "@iconscout/react-unicons/icons/uil-medical-drip";

var Impl = {};

function MedicalDrip(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilMedicalDrip, tmp);
}

var make = MedicalDrip;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
