// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilMedicalSquare from "@iconscout/react-unicons/icons/uil-medical-square";

var Impl = {};

function MedicalSquare(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilMedicalSquare, tmp);
}

var make = React.memo(MedicalSquare);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
