// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilMediumM from "@iconscout/react-unicons/icons/uil-medium-m";

var Impl = {};

function MediumM(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilMediumM, tmp);
}

var make = React.memo(MediumM);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
