// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilMegaphone from "@iconscout/react-unicons/icons/uil-megaphone";

var Impl = {};

function Megaphone(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilMegaphone, tmp);
}

var make = Megaphone;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
