// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilMehClosedEye from "@iconscout/react-unicons/icons/uil-meh-closed-eye";

var Impl = {};

function MehClosedEye(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilMehClosedEye, tmp);
}

var make = React.memo(MehClosedEye);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
