// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilMicrophoneSlash from "@iconscout/react-unicons/icons/uil-microphone-slash";

var Impl = {};

function MicrophoneSlash(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilMicrophoneSlash, tmp);
}

var make = MicrophoneSlash;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
