// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilMinusSquare from "@iconscout/react-unicons/icons/uil-minus-square";

var Impl = {};

function MinusSquare(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilMinusSquare, tmp);
}

var make = React.memo(MinusSquare);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
