// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilMissedCall from "@iconscout/react-unicons/icons/uil-missed-call";

var Impl = {};

function MissedCall(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilMissedCall, tmp);
}

var make = MissedCall;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
