// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilMobileVibrate from "@iconscout/react-unicons/icons/uil-mobile-vibrate";

var Impl = {};

function MobileVibrate(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilMobileVibrate, tmp);
}

var make = MobileVibrate;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
