// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilMobileAndroid from "@iconscout/react-unicons/icons/uil-mobile-android";

var Impl = {};

function MobileAndroid(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilMobileAndroid, tmp);
}

var make = React.memo(MobileAndroid);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
