// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilMoneyInsert from "@iconscout/react-unicons/icons/uil-money-insert";

var Impl = {};

function MoneyInsert(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilMoneyInsert, tmp);
}

var make = MoneyInsert;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
