// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilMonitorHeartRate from "@iconscout/react-unicons/icons/uil-monitor-heart-rate";

var Impl = {};

function MonitorHeartRate(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilMonitorHeartRate, tmp);
}

var make = React.memo(MonitorHeartRate);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
