// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilMouse from "@iconscout/react-unicons/icons/uil-mouse";

var Impl = {};

function Mouse(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilMouse, tmp);
}

var make = Mouse;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
