// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilMusicTuneSlash from "@iconscout/react-unicons/icons/uil-music-tune-slash";

var Impl = {};

function MusicTuneSlash(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilMusicTuneSlash, tmp);
}

var make = MusicTuneSlash;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
