// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilNerd from "@iconscout/react-unicons/icons/uil-nerd";

var Impl = {};

function Nerd(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilNerd, tmp);
}

var make = Nerd;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
