// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilNinja from "@iconscout/react-unicons/icons/uil-ninja";

var Impl = {};

function Ninja(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilNinja, tmp);
}

var make = Ninja;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
