// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilPanoramaV from "@iconscout/react-unicons/icons/uil-panorama-v";

var Impl = {};

function PanoramaV(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilPanoramaV, tmp);
}

var make = PanoramaV;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
