// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilParcel from "@iconscout/react-unicons/icons/uil-parcel";

var Impl = {};

function Parcel(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilParcel, tmp);
}

var make = Parcel;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
