// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilPaypal from "@iconscout/react-unicons/icons/uil-paypal";

var Impl = {};

function Paypal(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilPaypal, tmp);
}

var make = React.memo(Paypal);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
