// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilPresentationLine from "@iconscout/react-unicons/icons/uil-presentation-line";

var Impl = {};

function PresentationLine(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilPresentationLine, tmp);
}

var make = PresentationLine;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
