// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilPresentationMinus from "@iconscout/react-unicons/icons/uil-presentation-minus";

var Impl = {};

function PresentationMinus(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilPresentationMinus, tmp);
}

var make = React.memo(PresentationMinus);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
