// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilPricetagAlt from "@iconscout/react-unicons/icons/uil-pricetag-alt";

var Impl = {};

function PricetagAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilPricetagAlt, tmp);
}

var make = PricetagAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
