// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilPrint from "@iconscout/react-unicons/icons/uil-print";

var Impl = {};

function Print(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilPrint, tmp);
}

var make = Print;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
