// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilProgrammingLanguage from "@iconscout/react-unicons/icons/uil-programming-language";

var Impl = {};

function ProgrammingLanguage(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilProgrammingLanguage, tmp);
}

var make = ProgrammingLanguage;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
