// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilPuzzlePiece from "@iconscout/react-unicons/icons/uil-puzzle-piece";

var Impl = {};

function PuzzlePiece(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilPuzzlePiece, tmp);
}

var make = PuzzlePiece;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
