// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilQrcodeScan from "@iconscout/react-unicons/icons/uil-qrcode-scan";

var Impl = {};

function QrcodeScan(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilQrcodeScan, tmp);
}

var make = QrcodeScan;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
