// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilReceiptAlt from "@iconscout/react-unicons/icons/uil-receipt-alt";

var Impl = {};

function ReceiptAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilReceiptAlt, tmp);
}

var make = ReceiptAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
