// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilRedditAlienAlt from "@iconscout/react-unicons/icons/uil-reddit-alien-alt";

var Impl = {};

function RedditAlienAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilRedditAlienAlt, tmp);
}

var make = RedditAlienAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
