// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilRocket from "@iconscout/react-unicons/icons/uil-rocket";

var Impl = {};

function Rocket(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilRocket, tmp);
}

var make = Rocket;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
