// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilRotate from "@iconscout/react-unicons/icons/uil-rotate-360";

var Impl = {};

function Rotate360(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilRotate, tmp);
}

var make = React.memo(Rotate360);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
