// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilRssInterface from "@iconscout/react-unicons/icons/uil-rss-interface";

var Impl = {};

function RssInterface(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilRssInterface, tmp);
}

var make = RssInterface;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
