// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilSadDizzy from "@iconscout/react-unicons/icons/uil-sad-dizzy";

var Impl = {};

function SadDizzy(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilSadDizzy, tmp);
}

var make = SadDizzy;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
