// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilSanitizer from "@iconscout/react-unicons/icons/uil-sanitizer";

var Impl = {};

function Sanitizer(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilSanitizer, tmp);
}

var make = Sanitizer;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
