// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilSanitizerAlt from "@iconscout/react-unicons/icons/uil-sanitizer-alt";

var Impl = {};

function SanitizerAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilSanitizerAlt, tmp);
}

var make = React.memo(SanitizerAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
