// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilScalingRight from "@iconscout/react-unicons/icons/uil-scaling-right";

var Impl = {};

function ScalingRight(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilScalingRight, tmp);
}

var make = React.memo(ScalingRight);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
