// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilScalingLeft from "@iconscout/react-unicons/icons/uil-scaling-left";

var Impl = {};

function ScalingLeft(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilScalingLeft, tmp);
}

var make = ScalingLeft;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
