// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilSearchAlt from "@iconscout/react-unicons/icons/uil-search-alt";

var Impl = {};

function SearchAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilSearchAlt, tmp);
}

var make = React.memo(SearchAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
