// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilSearchMinus from "@iconscout/react-unicons/icons/uil-search-minus";

var Impl = {};

function SearchMinus(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilSearchMinus, tmp);
}

var make = SearchMinus;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
