// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilServerNetworkAlt from "@iconscout/react-unicons/icons/uil-server-network-alt";

var Impl = {};

function ServerNetworkAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilServerNetworkAlt, tmp);
}

var make = ServerNetworkAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
