// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilShieldPlus from "@iconscout/react-unicons/icons/uil-shield-plus";

var Impl = {};

function ShieldPlus(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilShieldPlus, tmp);
}

var make = React.memo(ShieldPlus);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
