// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilShoppingCart from "@iconscout/react-unicons/icons/uil-shopping-cart";

var Impl = {};

function ShoppingCart(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilShoppingCart, tmp);
}

var make = ShoppingCart;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
