// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilSignOutAlt from "@iconscout/react-unicons/icons/uil-sign-out-alt";

var Impl = {};

function SignOutAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilSignOutAlt, tmp);
}

var make = React.memo(SignOutAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
