// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilSignalAlt from "@iconscout/react-unicons/icons/uil-signal-alt";

var Impl = {};

function SignalAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilSignalAlt, tmp);
}

var make = React.memo(SignalAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
