// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilSimCard from "@iconscout/react-unicons/icons/uil-sim-card";

var Impl = {};

function SimCard(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilSimCard, tmp);
}

var make = React.memo(SimCard);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
