// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilSkipForward from "@iconscout/react-unicons/icons/uil-skip-forward";

var Impl = {};

function SkipForward(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilSkipForward, tmp);
}

var make = SkipForward;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
