// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilSlidersVAlt from "@iconscout/react-unicons/icons/uil-sliders-v-alt";

var Impl = {};

function SlidersVAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilSlidersVAlt, tmp);
}

var make = SlidersVAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
