// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilSlidersV from "@iconscout/react-unicons/icons/uil-sliders-v";

var Impl = {};

function SlidersV(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilSlidersV, tmp);
}

var make = React.memo(SlidersV);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
