// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilSmileDizzy from "@iconscout/react-unicons/icons/uil-smile-dizzy";

var Impl = {};

function SmileDizzy(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilSmileDizzy, tmp);
}

var make = SmileDizzy;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
