// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilSmileWink from "@iconscout/react-unicons/icons/uil-smile-wink";

var Impl = {};

function SmileWink(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilSmileWink, tmp);
}

var make = SmileWink;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
