// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilSmileWinkAlt from "@iconscout/react-unicons/icons/uil-smile-wink-alt";

var Impl = {};

function SmileWinkAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilSmileWinkAlt, tmp);
}

var make = React.memo(SmileWinkAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
