// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilSmileSquintWink from "@iconscout/react-unicons/icons/uil-smile-squint-wink";

var Impl = {};

function SmileSquintWink(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilSmileSquintWink, tmp);
}

var make = React.memo(SmileSquintWink);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
