// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilSnowflake from "@iconscout/react-unicons/icons/uil-snowflake";

var Impl = {};

function SnowFlake(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilSnowflake, tmp);
}

var make = React.memo(SnowFlake);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
