// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilSocialDistancing from "@iconscout/react-unicons/icons/uil-social-distancing";

var Impl = {};

function SocialDistancing(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilSocialDistancing, tmp);
}

var make = SocialDistancing;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
