// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilSortAmountUp from "@iconscout/react-unicons/icons/uil-sort-amount-up";

var Impl = {};

function SortAmountUp(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilSortAmountUp, tmp);
}

var make = SortAmountUp;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
