// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilSpaceKey from "@iconscout/react-unicons/icons/uil-space-key";

var Impl = {};

function SpaceKey(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilSpaceKey, tmp);
}

var make = SpaceKey;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
