// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilStarHalfAlt from "@iconscout/react-unicons/icons/uil-star-half-alt";

var Impl = {};

function StarHalfAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilStarHalfAlt, tmp);
}

var make = StarHalfAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
