// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilStepBackwardCircle from "@iconscout/react-unicons/icons/uil-step-backward-circle";

var Impl = {};

function StepBackwardCircle(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilStepBackwardCircle, tmp);
}

var make = StepBackwardCircle;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
