// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilStepForward from "@iconscout/react-unicons/icons/uil-step-forward";

var Impl = {};

function StepForward(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilStepForward, tmp);
}

var make = StepForward;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
