// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilStepBackwardAlt from "@iconscout/react-unicons/icons/uil-step-backward-alt";

var Impl = {};

function StepBackwardAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilStepBackwardAlt, tmp);
}

var make = React.memo(StepBackwardAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
