// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilStreering from "@iconscout/react-unicons/icons/uil-streering";

var Impl = {};

function Streering(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilStreering, tmp);
}

var make = Streering;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
