// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilSyncSlash from "@iconscout/react-unicons/icons/uil-sync-slash";

var Impl = {};

function SyncSlash(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilSyncSlash, tmp);
}

var make = SyncSlash;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
