// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilTablets from "@iconscout/react-unicons/icons/uil-tablets";

var Impl = {};

function Tablets(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilTablets, tmp);
}

var make = Tablets;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
