// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilTape from "@iconscout/react-unicons/icons/uil-tape";

var Impl = {};

function Tape(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilTape, tmp);
}

var make = Tape;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
