// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilTemperatureThreeQuarter from "@iconscout/react-unicons/icons/uil-temperature-three-quarter";

var Impl = {};

function TemperatureThreeQuarter(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilTemperatureThreeQuarter, tmp);
}

var make = TemperatureThreeQuarter;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
