// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilText from "@iconscout/react-unicons/icons/uil-text";

var Impl = {};

function $$Text(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilText, tmp);
}

var make = $$Text;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
