// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilTextStrikeThrough from "@iconscout/react-unicons/icons/uil-text-strike-through";

var Impl = {};

function TextStrikeThrough(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilTextStrikeThrough, tmp);
}

var make = React.memo(TextStrikeThrough);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
