// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilTextFields from "@iconscout/react-unicons/icons/uil-text-fields";

var Impl = {};

function TextFields(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilTextFields, tmp);
}

var make = TextFields;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
