// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilToggleOn from "@iconscout/react-unicons/icons/uil-toggle-on";

var Impl = {};

function ToggleOn(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilToggleOn, tmp);
}

var make = ToggleOn;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
