// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilToggleOff from "@iconscout/react-unicons/icons/uil-toggle-off";

var Impl = {};

function ToggleOff(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilToggleOff, tmp);
}

var make = ToggleOff;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
