// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilTopArrowFromTop from "@iconscout/react-unicons/icons/uil-top-arrow-from-top";

var Impl = {};

function TopArrowFromTop(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilTopArrowFromTop, tmp);
}

var make = TopArrowFromTop;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
