// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilTruckLoading from "@iconscout/react-unicons/icons/uil-truck-loading";

var Impl = {};

function TruckLoading(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilTruckLoading, tmp);
}

var make = React.memo(TruckLoading);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
