// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilTruck from "@iconscout/react-unicons/icons/uil-truck";

var Impl = {};

function Truck(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilTruck, tmp);
}

var make = Truck;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
