// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilTvRetroSlash from "@iconscout/react-unicons/icons/uil-tv-retro-slash";

var Impl = {};

function TvRetroSlash(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilTvRetroSlash, tmp);
}

var make = TvRetroSlash;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
