// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilTvRetro from "@iconscout/react-unicons/icons/uil-tv-retro";

var Impl = {};

function TvRetro(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilTvRetro, tmp);
}

var make = TvRetro;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
