// Generated by ReScript, PLEASE EDIT WITH CARE


var Abacus = {};

var AccessibleIconAlt = {};

var AdjustAlt = {};

var AdjustCircle = {};

var AdjustHalf = {};

var Adjust = {};

var AdobeAlt = {};

var Adobe = {};

var Airplay = {};

var AlignAlt = {};

var AlignCenterAlt = {};

var AlignCenterH = {};

var AlignCenterJustify = {};

var AlignCenterV = {};

var AlignCenter = {};

var AlignJustify = {};

var AlignLeftJustify = {};

var AlignLeft = {};

var AlignLetterRight = {};

var AlignRightJustify = {};

var AlignRight = {};

var Align = {};

var Amazon = {};

var Ambulance = {};

var Analysis = {};

var Analytics = {};

var Anchor = {};

var AndroidAlt = {};

var AndroidPhoneSlash = {};

var Android = {};

var AngleDoubleDown = {};

var AngleDoubleLeft = {};

var AngleDoubleRight = {};

var AngleDoubleUp = {};

var AngleDown = {};

var AngleLeftB = {};

var AngleLeft = {};

var AngleRightB = {};

var AngleRight = {};

var AngleUp = {};

var Angry = {};

var Ankh = {};

var AnnoyedAlt = {};

var Annoyed = {};

var AppleAlt = {};

var Apple = {};

var Apps = {};

var ArchiveAlt = {};

var Archive = {};

var Archway = {};

var ArrowBreak = {};

var ArrowCircleDown = {};

var ArrowCircleLeft = {};

var ArrowCircleRight = {};

var ArrowCircleUp = {};

var ArrowCompressH = {};

var ArrowDownLeft = {};

var ArrowDownRight = {};

var ArrowDown = {};

var ArrowFromRight = {};

var ArrowFromTop = {};

var ArrowGrowth = {};

var ArrowLeft = {};

var ArrowRandom = {};

var ArrowResizeDiagonal = {};

var ArrowRight = {};

var ArrowToBottom = {};

var ArrowToRight = {};

var ArrowUpLeft = {};

var ArrowUpRight = {};

var ArrowUp = {};

var Arrow = {};

var ArrowsHAlt = {};

var ArrowsH = {};

var ArrowsLeftDown = {};

var ArrowsMaximize = {};

var ArrowsMerge = {};

var ArrowsResizeH = {};

var ArrowsResizeV = {};

var ArrowsResize = {};

var ArrowsRightDown = {};

var ArrowsShrinkH = {};

var ArrowsShrinkV = {};

var ArrowsUpRight = {};

var ArrowsVAlt = {};

var ArrowsV = {};

var AssistiveListeningSystems = {};

var Asterisk = {};

var At = {};

var Atom = {};

var AutoFlash = {};

var AwardAlt = {};

var Award = {};

var BabyCarriage = {};

var Backpack = {};

var Backspace = {};

var Backward = {};

var BagAlt = {};

var BagSlash = {};

var Bag = {};

var BalanceScale = {};

var Ban = {};

var BandAid = {};

var Bars = {};

var BaseballBall = {};

var BasketballHoop = {};

var Basketball = {};

var Bath = {};

var BatteryBolt = {};

var BatteryEmpty = {};

var BedDouble = {};

var Bed = {};

var BehanceAlt = {};

var Behance = {};

var BellSchool = {};

var BellSlash = {};

var Bell = {};

var Bill = {};

var Bing = {};

var BitcoinAlt = {};

var BitcoinCircle = {};

var BitcoinSign = {};

var Bitcoin = {};

var BlackBerry = {};

var BloggerAlt = {};

var Blogger = {};

var BluetoothB = {};

var Bold = {};

var BoltAlt = {};

var BoltSlash = {};

var Bolt = {};

var BookAlt = {};

var BookMedical = {};

var BookOpen = {};

var BookReader = {};

var Book = {};

var BookmarkFull = {};

var Bookmark = {};

var Books = {};

var Boombox = {};

var BorderAlt = {};

var BorderBottom = {};

var BorderClear = {};

var BorderHorizontal = {};

var BorderInner = {};

var BorderLeft = {};

var BorderOut = {};

var BorderRight = {};

var BorderTop = {};

var BorderVertical = {};

var BowlingBall = {};

var Box = {};

var BracketsCurly = {};

var Brain = {};

var BriefcaseAlt = {};

var Briefcase = {};

var Bright = {};

var BrightnessEmpty = {};

var BrightnessHalf = {};

var BrightnessLow = {};

var BrightnessMinus = {};

var BrightnessPlus = {};

var Brightness = {};

var BringBottom = {};

var BringFront = {};

var Browser = {};

var BrushAlt = {};

var Bug = {};

var Building = {};

var Bullseye = {};

var BusAlt = {};

var BusSchool = {};

var Bus = {};

var CalculatorAlt = {};

var Calculator = {};

var CalendarAlt = {};

var CalendarSlash = {};

var Calender = {};

var Calling = {};

var CameraChange = {};

var CameraPlus = {};

var CameraSlash = {};

var Camera = {};

var Cancel = {};

var Capsule = {};

var Capture = {};

var CarSideview = {};

var CarSlash = {};

var CarWash = {};

var Car = {};

var CardAtm = {};

var CaretRight = {};

var Cell = {};

var Celsius = {};

var ChannelAdd = {};

var Channel = {};

var ChartBarAlt = {};

var ChartBar = {};

var ChartDown = {};

var ChartGrowthAlt = {};

var ChartGrowth = {};

var ChartLine = {};

var ChartPieAlt = {};

var ChartPie = {};

var Chart = {};

var ChatBubbleUser = {};

var ChatInfo = {};

var Chat = {};

var CheckCircle = {};

var CheckSquare = {};

var Check = {};

var CircleLayer = {};

var Circle = {};

var Circuit = {};

var ClapperBoard = {};

var ClinicMedical = {};

var ClipboardAlt = {};

var ClipboardBlank = {};

var ClipboardNotes = {};

var Clipboard = {};

var ClockEight = {};

var ClockFive = {};

var ClockNine = {};

var ClockSeven = {};

var ClockTen = {};

var ClockThree = {};

var ClockTwo = {};

var Clock = {};

var ClosedCaptioningSlash = {};

var ClosedCaptioning = {};

var CloudBlock = {};

var CloudBookmark = {};

var CloudCheck = {};

var CloudComputing = {};

var CloudDataConnection = {};

var CloudDatabaseTree = {};

var CloudDownload = {};

var CloudDrizzle = {};

var CloudExclamation = {};

var CloudHail = {};

var CloudHeart = {};

var CloudInfo = {};

var CloudLock = {};

var CloudMeatball = {};

var CloudMoonHail = {};

var CloudMoonMeatball = {};

var CloudMoonRain = {};

var CloudMoonShowers = {};

var CloudMoon = {};

var CloudQuestion = {};

var CloudRainSun = {};

var CloudRain = {};

var CloudRedo = {};

var CloudShare = {};

var CloudShield = {};

var CloudShowersAlt = {};

var CloudShowersHeavy = {};

var CloudShowers = {};

var CloudSlash = {};

var CloudSunHail = {};

var CloudSunMeatball = {};

var CloudSunRainAlt = {};

var CloudSunRain = {};

var CloudSunTear = {};

var CloudSun = {};

var CloudTimes = {};

var CloudUnlock = {};

var CloudUpload = {};

var CloudWifi = {};

var CloudWind = {};

var Cloud = {};

var Clouds = {};

var Club = {};

var CodeBranch = {};

var Coffee = {};

var Cog = {};

var Coins = {};

var Columns = {};

var CommentAdd = {};

var CommentAltBlock = {};

var CommentAltChartLines = {};

var CommentAltCheck = {};

var CommentAltDots = {};

var CommentAltDownload = {};

var CommentAltEdit = {};

var CommentAltExclamation = {};

var CommentAltHeart = {};

var CommentAltImage = {};

var CommentAltInfo = {};

var CommentAltLines = {};

var CommentAltLock = {};

var CommentAltMedical = {};

var CommentAltMessage = {};

var CommentAltNotes = {};

var CommentAltPlus = {};

var CommentAltQuestion = {};

var CommentAltRedo = {};

var CommentAltSearch = {};

var CommentAltShare = {};

var CommentAltShield = {};

var CommentAltSlash = {};

var CommentAltUpload = {};

var CommentAltVerify = {};

var CommentAlt = {};

var CommentBlock = {};

var CommentChartLine = {};

var CommentCheck = {};

var CommentDots = {};

var CommentDownload = {};

var CommentEdit = {};

var CommentExclamation = {};

var CommentHeart = {};

var CommentImage = {};

var CommentInfoAlt = {};

var CommentInfo = {};

var CommentLines = {};

var CommentLock = {};

var CommentMedical = {};

var CommentMessage = {};

var CommentNotes = {};

var CommentPlus = {};

var CommentQuestion = {};

var CommentRedo = {};

var CommentSearch = {};

var CommentShare = {};

var CommentShield = {};

var CommentSlash = {};

var CommentUpload = {};

var CommentVerify = {};

var $$Comment = {};

var CommentsAlt = {};

var Comments = {};

var CompactDisc = {};

var Comparison = {};

var Compass = {};

var CompressAltLeft = {};

var CompressAlt = {};

var CompressArrows = {};

var CompressLines = {};

var CompressPoint = {};

var CompressV = {};

var Compress = {};

var Confused = {};

var Constructor = {};

var CopyAlt = {};

var CopyLandscape = {};

var Copy = {};

var Copyright = {};

var CornerDownLeft = {};

var CornerDownRightAlt = {};

var CornerDownRight = {};

var CornerLeftDown = {};

var CornerRightDown = {};

var CornerUpLeftAlt = {};

var CornerUpLeft = {};

var CornerUpRightAlt = {};

var CornerUpRight = {};

var Coronavirus = {};

var CreateDashboard = {};

var CreativeCommonsPd = {};

var CreditCardSearch = {};

var CreditCard = {};

var Crockery = {};

var CropAltRotateLeft = {};

var CropAltRotateRight = {};

var CropAlt = {};

var CrosshairAlt = {};

var Crosshair = {};

var Crosshairs = {};

var Css3Simple = {};

var Cube = {};

var Dashboard = {};

var DataSharing = {};

var DatabaseAlt = {};

var Database = {};

var Desert = {};

var DesktopAltSlash = {};

var DesktopAlt = {};

var DesktopCloudAlt = {};

var DesktopSlash = {};

var Desktop = {};

var DialpadAlt = {};

var Dialpad = {};

var Diamond = {};

var DiaryAlt = {};

var Diary = {};

var DiceFive = {};

var DiceFour = {};

var DiceOne = {};

var DiceSix = {};

var DiceThree = {};

var DiceTwo = {};

var Direction = {};

var Directions = {};

var Discord = {};

var DizzyMeh = {};

var Dna = {};

var Docker = {};

var DocumentInfo = {};

var DocumentLayoutCenter = {};

var DocumentLayoutLeft = {};

var DocumentLayoutRight = {};

var DollarAlt = {};

var DollarSignAlt = {};

var DollarSign = {};

var DownloadAlt = {};

var Draggabledots = {};

var Dribbble = {};

var Drill = {};

var Dropbox = {};

var Dumbbell = {};

var Ear = {};

var EditAlt = {};

var Edit = {};

var ElipsisDoubleVAlt = {};

var EllipsisH = {};

var EllipsisV = {};

var Emoji = {};

var EnglishToChinese = {};

var Enter = {};

var EnvelopeAdd = {};

var EnvelopeAlt = {};

var EnvelopeBlock = {};

var EnvelopeBookmark = {};

var EnvelopeCheck = {};

var EnvelopeDownloadAlt = {};

var EnvelopeDownload = {};

var EnvelopeEdit = {};

var EnvelopeExclamation = {};

var EnvelopeHeart = {};

var EnvelopeInfo = {};

var EnvelopeLock = {};

var EnvelopeMinus = {};

var EnvelopeOpen = {};

var EnvelopeQuestion = {};

var EnvelopeReceive = {};

var EnvelopeRedo = {};

var EnvelopeSearch = {};

var EnvelopeSend = {};

var EnvelopeShare = {};

var EnvelopeShield = {};

var EnvelopeStar = {};

var EnvelopeTimes = {};

var EnvelopeUploadAlt = {};

var EnvelopeUpload = {};

var Envelope = {};

var Envelopes = {};

var EqualCircle = {};

var Estate = {};

var EuroCircle = {};

var Euro = {};

var ExchangeAlt = {};

var Exchange = {};

var ExclamationCircle = {};

var ExclamationOctagon = {};

var ExclamationTriangle = {};

var Exclamation = {};

var Exclude = {};

var ExpandAlt = {};

var ExpandArrowsAlt = {};

var ExpandArrows = {};

var ExpandFromCorner = {};

var ExpandLeft = {};

var ExpandRight = {};

var Export = {};

var ExposureAlt = {};

var ExposureIncrease = {};

var ExternalLinkAlt = {};

var EyeSlash = {};

var Eye = {};

var FacebookF = {};

var FacebookMessengerAlt = {};

var FacebookMessenger = {};

var Facebook = {};

var Fahrenheit = {};

var FastMailAlt = {};

var FastMail = {};

var Favorite = {};

var Feedback = {};

var FidgetSpinner = {};

var FileAlt = {};

var FileBlank = {};

var FileBlockAlt = {};

var FileBookmarkAlt = {};

var FileCheckAlt = {};

var FileCheck = {};

var FileContractDollar = {};

var FileContract = {};

var FileCopyAlt = {};

var FileDownloadAlt = {};

var FileDownload = {};

var FileEditAlt = {};

var FileExclamationAlt = {};

var FileExclamation = {};

var FileExport = {};

var FileGraph = {};

var FileHeart = {};

var FileImport = {};

var FileInfoAlt = {};

var FileLandscapeAlt = {};

var FileLandscape = {};

var FileLanscapeSlash = {};

var FileLockAlt = {};

var FileMedicalAlt = {};

var FileMedical = {};

var FileMinusAlt = {};

var FileMinus = {};

var FileNetwork = {};

var FilePlusAlt = {};

var FilePlus = {};

var FileQuestionAlt = {};

var FileQuestion = {};

var FileRedoAlt = {};

var FileSearchAlt = {};

var FileShareAlt = {};

var FileShieldAlt = {};

var FileSlash = {};

var FileTimesAlt = {};

var FileTimes = {};

var FileUploadAlt = {};

var FileUpload = {};

var $$File = {};

var FilesLandscapesAlt = {};

var FilesLandscapes = {};

var Film = {};

var FilterSlash = {};

var Filter = {};

var Fire = {};

var FlaskPotion = {};

var Flask = {};

var FlipHAlt = {};

var FlipH = {};

var FlipVAlt = {};

var FlipV = {};

var Flower = {};

var FocusAdd = {};

var FocusTarget = {};

var Focus = {};

var FolderCheck = {};

var FolderDownload = {};

var FolderExclamation = {};

var FolderHeart = {};

var FolderInfo = {};

var FolderLock = {};

var FolderMedical = {};

var FolderMinus = {};

var FolderNetwork = {};

var FolderOpen = {};

var FolderPlus = {};

var FolderQuestion = {};

var FolderSlash = {};

var FolderTimes = {};

var FolderUpload = {};

var Folder = {};

var Font = {};

var FootballAmerican = {};

var FootballBall = {};

var Football = {};

var ForecastcloudMoonTear = {};

var ForwadedCall = {};

var Forward = {};

var Frown = {};

var GameStructure = {};

var Gift = {};

var GithubAlt = {};

var Github = {};

var Gitlab = {};

var GlassMartiniAltSlash = {};

var GlassMartiniAlt = {};

var GlassMartini = {};

var GlassTea = {};

var Glass = {};

var Globe = {};

var Gold = {};

var GolfBall = {};

var GoogleDriveAlt = {};

var GoogleDrive = {};

var GoogleHangoutsAlt = {};

var GoogleHangouts = {};

var GooglePlay = {};

var Google = {};

var GraduationCap = {};

var GraphBar = {};

var Grid = {};

var Grids = {};

var GrinTongueWinkAlt = {};

var GrinTongueWink = {};

var Grin = {};

var GripHorizontalLine = {};

var HardHat = {};

var Hdd = {};

var HeadSideCough = {};

var HeadSideMask = {};

var HeadSide = {};

var HeadphoneSlash = {};

var HeadphonesAlt = {};

var Headphones = {};

var HeartAlt = {};

var HeartBreak = {};

var HeartMedical = {};

var HeartRate = {};

var HeartSign = {};

var Heart = {};

var Heartbeat = {};

var HindiToChinese = {};

var Hipchat = {};

var HistoryAlt = {};

var $$History = {};

var Home = {};

var HorizontalAlignCenter = {};

var HorizontalAlignLeft = {};

var HorizontalAlignRight = {};

var HorizontalDistributionCenter = {};

var HorizontalDistributionLeft = {};

var HorizontalDistributionRight = {};

var HospitalSquareSign = {};

var HospitalSymbol = {};

var Hospital = {};

var Hourglass = {};

var HouseUser = {};

var Html3Alt = {};

var Html3 = {};

var Html5Alt = {};

var Html5 = {};

var Hunting = {};

var Icons = {};

var Illustration = {};

var ImageAltSlash = {};

var ImageBlock = {};

var ImageBroken = {};

var ImageCheck = {};

var ImageDownload = {};

var ImageEdit = {};

var ImageLock = {};

var ImageMinus = {};

var ImagePlus = {};

var ImageQuestion = {};

var ImageRedo = {};

var ImageResizeLandscape = {};

var ImageResizeSquare = {};

var ImageSearch = {};

var ImageShare = {};

var ImageShield = {};

var ImageSlash = {};

var ImageTimes = {};

var ImageUpload = {};

var ImageV = {};

var $$Image = {};

var Images = {};

var Import = {};

var Inbox = {};

var IncomingCall = {};

var InfoCircle = {};

var Info = {};

var InstagramAlt = {};

var Instagram = {};

var IntercomAlt = {};

var Intercom = {};

var Invoice = {};

var Italic = {};

var Jackhammer = {};

var JavaScript = {};

var Kayak = {};

var KeySkeletonAlt = {};

var KeySkeleton = {};

var KeyboardAlt = {};

var KeyboardHide = {};

var KeyboardShow = {};

var Keyboard = {};

var KeyholeCircle = {};

var KeyholeSquareFull = {};

var KeyholeSquare = {};

var Kid = {};

var LabelAlt = {};

var Label = {};

var Lamp = {};

var Language = {};

var LaptopCloud = {};

var LaptopConnection = {};

var Laptop = {};

var Laughing = {};

var LayerGroupSlash = {};

var LayerGroup = {};

var LayersAlt = {};

var LayersSlash = {};

var Layers = {};

var LeftArrowFromLeft = {};

var LeftArrowToLeft = {};

var LeftIndentAlt = {};

var LeftIndent = {};

var LeftToRightTextDirection = {};

var LetterChineseA = {};

var LetterEnglishA = {};

var LetterHindiA = {};

var LetterJapaneseA = {};

var LifeRing = {};

var LightbulbAlt = {};

var Lightbulb = {};

var LineAlt = {};

var LineSpacing = {};

var Line = {};

var LinkAdd = {};

var LinkAlt = {};

var LinkBroken = {};

var LinkH = {};

var Link = {};

var LinkedinAlt = {};

var Linkedin = {};

var Linux = {};

var LiraSign = {};

var ListOlAlt = {};

var ListOl = {};

var ListUiAlt = {};

var ListUl = {};

var LocationArrowAlt = {};

var LocationArrow = {};

var LocationPinAlt = {};

var LocationPoint = {};

var LockAccess = {};

var LockAlt = {};

var LockOpenAlt = {};

var LockSlash = {};

var Lock = {};

var LottiefilesAlt = {};

var Lottiefiles = {};

var LuggageCart = {};

var MailboxAlt = {};

var Mailbox = {};

var MapMarkerAlt = {};

var MapMarkerEdit = {};

var MapMarkerInfo = {};

var MapMarkerMinus = {};

var MapMarkerPlus = {};

var MapMarkerQuestion = {};

var MapMarkerShield = {};

var MapMarkerSlash = {};

var MapMarker = {};

var MapPinAlt = {};

var MapPin = {};

var $$Map = {};

var Mars = {};

var MasterCard = {};

var MaximizeLeft = {};

var Medal = {};

var MedicalDrip = {};

var MedicalSquareFull = {};

var MedicalSquare = {};

var MediumM = {};

var Medkit = {};

var MeetingBoard = {};

var Megaphone = {};

var MehAlt = {};

var MehClosedEye = {};

var Meh = {};

var Message = {};

var Metro = {};

var MicrophoneSlash = {};

var Microphone = {};

var Microscope = {};

var Microsoft = {};

var MinusCircle = {};

var MinusPath = {};

var MinusSquareFull = {};

var MinusSquare = {};

var Minus = {};

var MissedCall = {};

var MobileAndroidAlt = {};

var MobileAndroid = {};

var MobileVibrate = {};

var Modem = {};

var MoneyBillSlash = {};

var MoneyBillStack = {};

var MoneyBill = {};

var MoneyInsert = {};

var MoneyStack = {};

var MoneyWithdraw = {};

var MoneyWithdrawal = {};

var MoneybagAlt = {};

var Moneybag = {};

var MonitorHeartRate = {};

var Monitor = {};

var MoonEclipse = {};

var Moon = {};

var Moonset = {};

var MountainsSun = {};

var Mountains = {};

var MouseAlt2 = {};

var MouseAlt = {};

var Mouse = {};

var Multiply = {};

var MusicNote = {};

var MusicTuneSlash = {};

var Music = {};

var NA = {};

var $$Navigator = {};

var Nerd = {};

var Newspaper = {};

var Ninja = {};

var NoEntry = {};

var Notebooks = {};

var Notes = {};

var ObjectGroup = {};

var ObjectUngroup = {};

var Octagon = {};

var Okta = {};

var OperaAlt = {};

var Opera = {};

var OutgoingCall = {};

var Package = {};

var Padlock = {};

var Pagelines = {};

var Pagerduty = {};

var PaintTool = {};

var Palette = {};

var PanelAdd = {};

var PanoramaHAlt = {};

var PanoramaH = {};

var PanoramaV = {};

var Paperclip = {};

var Paragraph = {};

var Parcel = {};

var ParkingCircle = {};

var ParkingSquare = {};

var PathfinderUnite = {};

var Pathfinder = {};

var PauseCircle = {};

var Pause = {};

var Paypal = {};

var Pen = {};

var Pentagon = {};

var Percentage = {};

var PhoneAlt = {};

var PhonePause = {};

var PhoneSlash = {};

var PhoneTimes = {};

var PhoneVolume = {};

var Phone = {};

var Picture = {};

var PizzaSlice = {};

var PlaneArrival = {};

var PlaneDeparture = {};

var PlaneFly = {};

var Plane = {};

var PlayCircle = {};

var Play = {};

var Plug = {};

var PlusCircle = {};

var PlusSquare = {};

var Plus = {};

var Podium = {};

var Polygon = {};

var PostStamp = {};

var Postcard = {};

var PoundCircle = {};

var Pound = {};

var Power = {};

var PrescriptionBottle = {};

var PresentationCheck = {};

var PresentationEdit = {};

var PresentationLine = {};

var PresentationLinesAlt = {};

var PresentationMinus = {};

var PresentationPlay = {};

var PresentationPlus = {};

var PresentationTimes = {};

var Presentation = {};

var Previous = {};

var PricetagAlt = {};

var PrintSlash = {};

var Print = {};

var Process = {};

var Processor = {};

var ProgrammingLanguage = {};

var Pump = {};

var PuzzlePiece = {};

var QrcodeScan = {};

var QuestionCircle = {};

var Question = {};

var Rainbow = {};

var RaindropsAlt = {};

var Raindrops = {};

var ReceiptAlt = {};

var Receipt = {};

var RecordAudio = {};

var RedditAlienAlt = {};

var Redo = {};

var Refresh = {};

var Registered = {};

var Repeat = {};

var Restaurant = {};

var RightIndentAlt = {};

var RightToLeftTextDirection = {};

var Robot = {};

var Rocket = {};

var RopeWay = {};

var Rotate360 = {};

var RssAlt = {};

var RssInterface = {};

var Rss = {};

var RulerCombined = {};

var Ruler = {};

var RupeeSign = {};

var SadCry = {};

var SadCrying = {};

var SadDizzy = {};

var SadSquint = {};

var Sad = {};

var SanitizerAlt = {};

var Sanitizer = {};

var Save = {};

var ScalingLeft = {};

var ScalingRight = {};

var Scenery = {};

var Schedule = {};

var Screw = {};

var ScrollH = {};

var Scroll = {};

var SearchAlt = {};

var SearchMinus = {};

var SearchPlus = {};

var Search = {};

var Selfie = {};

var ServerAlt = {};

var ServerConnection = {};

var ServerNetworkAlt = {};

var ServerNetwork = {};

var Server = {};

var Servers = {};

var Servicemark = {};

var Setting = {};

var ShareAlt = {};

var Share = {};

var ShieldCheck = {};

var ShieldExclamation = {};

var ShieldPlus = {};

var ShieldQuestion = {};

var ShieldSlash = {};

var Shield = {};

var Ship = {};

var Shop = {};

var ShoppingBag = {};

var ShoppingBasket = {};

var ShoppingCartAlt = {};

var ShoppingCart = {};

var Shovel = {};

var Shrink = {};

var Shuffle = {};

var ShutterAlt = {};

var Shutter = {};

var Sick = {};

var Sigma = {};

var SignAlt = {};

var SignInAlt = {};

var SignLeft = {};

var SignOutAlt = {};

var SignRight = {};

var SignalAlt3 = {};

var SignalAlt = {};

var Signal = {};

var Signin = {};

var Signout = {};

var Silence = {};

var SilentSquint = {};

var SimCard = {};

var Sitemap = {};

var SkipForwardAlt = {};

var SkipForwardCircle = {};

var SkipForward = {};

var SkypeAlt = {};

var Skype = {};

var SlackAlt = {};

var Slack = {};

var SliderHRange = {};

var SliderH = {};

var SlidersVAlt = {};

var SlidersV = {};

var SmileBeam = {};

var SmileDizzy = {};

var SmileSquintWinkAlt = {};

var SmileSquintWink = {};

var SmileWinkAlt = {};

var SmileWink = {};

var Smile = {};

var SnapchatAlt = {};

var SnapchatGhost = {};

var SnapchatSquare = {};

var SnowFlake = {};

var SnowflakeAlt = {};

var Snowflake = {};

var SocialDistancing = {};

var SortAmountDown = {};

var SortAmountUp = {};

var Sort = {};

var Sorting = {};

var SpaceKey = {};

var Spade = {};

var Sperms = {};

var Spin = {};

var SpinnerAlt = {};

var Spinner = {};

var SquareFull = {};

var SquareShape = {};

var Square = {};

var Squint = {};

var StarHalfAlt = {};

var Star = {};

var StepBackwardAlt = {};

var StepBackwardCircle = {};

var StepBackward = {};

var StepForward = {};

var StethoscopeAlt = {};

var Stethoscope = {};

var StopCircle = {};

var StopwatchSlash = {};

var Stopwatch = {};

var StoreAlt = {};

var StoreSlash = {};

var Store = {};

var Streering = {};

var Stretcher = {};

var Subject = {};

var SubwayAlt = {};

var Subway = {};

var SuitcaseAlt = {};

var Suitcase = {};

var Sun = {};

var Sunset = {};

var Surprise = {};

var Swatchbook = {};

var Swiggy = {};

var Swimmer = {};

var SyncExclamation = {};

var SyncSlash = {};

var Sync = {};

var Syringe = {};

var TableTennis = {};

var Table = {};

var Tablet = {};

var Tablets = {};

var TachometerFastAlt = {};

var TachometerFast = {};

var TagAlt = {};

var Tag = {};

var Tape = {};

var Taxi = {};

var Tear = {};

var TelegramAlt = {};

var Telegram = {};

var Telescope = {};

var TemperatureEmpty = {};

var TemperatureHalf = {};

var TemperatureMinus = {};

var TemperaturePlus = {};

var TemperatureQuarter = {};

var TemperatureThreeQuarter = {};

var Temperature = {};

var TennisBall = {};

var TextFields = {};

var TextSize = {};

var TextStrikeThrough = {};

var $$Text = {};

var ThLarge = {};

var ThSlash = {};

var Th = {};

var Thermometer = {};

var ThumbsDown = {};

var ThumbsUp = {};

var ThunderstormMoon = {};

var ThunderstormSun = {};

var Thunderstorm = {};

var Ticket = {};

var TimesCircle = {};

var TimesSquare = {};

var Times = {};

var ToggleOff = {};

var ToggleOn = {};

var ToiletPaper = {};

var TopArrowFromTop = {};

var TopArrowToTop = {};

var Tornado = {};

var TrademarkCircle = {};

var Trademark = {};

var TrafficBarrier = {};

var TrafficLight = {};

var Transaction = {};

var TrashAlt = {};

var Trash = {};

var Trees = {};

var Triangle = {};

var Trophy = {};

var Trowel = {};

var TruckLoading = {};

var Truck = {};

var TumblrAlt = {};

var TumblrSquare = {};

var Tumblr = {};

var TvRetroSlash = {};

var TvRetro = {};

var TwitterAlt = {};

var Twitter = {};

var Umbrella = {};

var Unamused = {};

var Underline = {};

var University = {};

var UnlockAlt = {};

var Unlock = {};

var UploadAlt = {};

var Upload = {};

var UsdCircle = {};

var UsdSquare = {};

var UserArrows = {};

var UserCheck = {};

var UserCircle = {};

var UserExclamation = {};

var UserLocation = {};

var UserMd = {};

var UserMinus = {};

var UserNurse = {};

var UserPlus = {};

var UserSquare = {};

var UserTimes = {};

var User = {};

var UsersAlt = {};

var UtensilsAlt = {};

var Utensils = {};

var VectorSquareAlt = {};

var VectorSquare = {};

var Venus = {};

var VerticalAlignBottom = {};

var VerticalAlignCenter = {};

var VerticalAlignTop = {};

var VerticalDistributeBottom = {};

var VerticalDistributionCenter = {};

var VerticalDistributionTop = {};

var VideoQuestion = {};

var VideoSlash = {};

var Video = {};

var VirusSlash = {};

var VisualStudio = {};

var VkAlt = {};

var Vk = {};

var VoicemailRectangle = {};

var Voicemail = {};

var Volleyball = {};

var VolumeDown = {};

var VolumeMute = {};

var VolumeOff = {};

var VolumeUp = {};

var Volume = {};

var VuejsAlt = {};

var Vuejs = {};

var Wall = {};

var Wallet = {};

var WatchAlt = {};

var Watch = {};

var WaterDropSlash = {};

var WaterGlass = {};

var Water = {};

var WebGridAlt = {};

var WebGrid = {};

var WebSectionAlt = {};

var WebSection = {};

var Webcam = {};

var Weight = {};

var WhatsappAlt = {};

var Whatsapp = {};

var WheelBarrow = {};

var WheelchairAlt = {};

var Wheelchair = {};

var WifiRouter = {};

var WifiSlash = {};

var Wifi = {};

var WindMoon = {};

var WindSun = {};

var Wind = {};

var WindowGrid = {};

var WindowMaximize = {};

var WindowSection = {};

var $$Window = {};

var Windows = {};

var Windsock = {};

var Windy = {};

var WordpressSimple = {};

var Wordpress = {};

var WrapText = {};

var Wrench = {};

var XAdd = {};

var X = {};

var YenCircle = {};

var Yen = {};

var YinYang = {};

var Youtube = {};

export {
  Abacus ,
  AccessibleIconAlt ,
  AdjustAlt ,
  AdjustCircle ,
  AdjustHalf ,
  Adjust ,
  AdobeAlt ,
  Adobe ,
  Airplay ,
  AlignAlt ,
  AlignCenterAlt ,
  AlignCenterH ,
  AlignCenterJustify ,
  AlignCenterV ,
  AlignCenter ,
  AlignJustify ,
  AlignLeftJustify ,
  AlignLeft ,
  AlignLetterRight ,
  AlignRightJustify ,
  AlignRight ,
  Align ,
  Amazon ,
  Ambulance ,
  Analysis ,
  Analytics ,
  Anchor ,
  AndroidAlt ,
  AndroidPhoneSlash ,
  Android ,
  AngleDoubleDown ,
  AngleDoubleLeft ,
  AngleDoubleRight ,
  AngleDoubleUp ,
  AngleDown ,
  AngleLeftB ,
  AngleLeft ,
  AngleRightB ,
  AngleRight ,
  AngleUp ,
  Angry ,
  Ankh ,
  AnnoyedAlt ,
  Annoyed ,
  AppleAlt ,
  Apple ,
  Apps ,
  ArchiveAlt ,
  Archive ,
  Archway ,
  ArrowBreak ,
  ArrowCircleDown ,
  ArrowCircleLeft ,
  ArrowCircleRight ,
  ArrowCircleUp ,
  ArrowCompressH ,
  ArrowDownLeft ,
  ArrowDownRight ,
  ArrowDown ,
  ArrowFromRight ,
  ArrowFromTop ,
  ArrowGrowth ,
  ArrowLeft ,
  ArrowRandom ,
  ArrowResizeDiagonal ,
  ArrowRight ,
  ArrowToBottom ,
  ArrowToRight ,
  ArrowUpLeft ,
  ArrowUpRight ,
  ArrowUp ,
  Arrow ,
  ArrowsHAlt ,
  ArrowsH ,
  ArrowsLeftDown ,
  ArrowsMaximize ,
  ArrowsMerge ,
  ArrowsResizeH ,
  ArrowsResizeV ,
  ArrowsResize ,
  ArrowsRightDown ,
  ArrowsShrinkH ,
  ArrowsShrinkV ,
  ArrowsUpRight ,
  ArrowsVAlt ,
  ArrowsV ,
  AssistiveListeningSystems ,
  Asterisk ,
  At ,
  Atom ,
  AutoFlash ,
  AwardAlt ,
  Award ,
  BabyCarriage ,
  Backpack ,
  Backspace ,
  Backward ,
  BagAlt ,
  BagSlash ,
  Bag ,
  BalanceScale ,
  Ban ,
  BandAid ,
  Bars ,
  BaseballBall ,
  BasketballHoop ,
  Basketball ,
  Bath ,
  BatteryBolt ,
  BatteryEmpty ,
  BedDouble ,
  Bed ,
  BehanceAlt ,
  Behance ,
  BellSchool ,
  BellSlash ,
  Bell ,
  Bill ,
  Bing ,
  BitcoinAlt ,
  BitcoinCircle ,
  BitcoinSign ,
  Bitcoin ,
  BlackBerry ,
  BloggerAlt ,
  Blogger ,
  BluetoothB ,
  Bold ,
  BoltAlt ,
  BoltSlash ,
  Bolt ,
  BookAlt ,
  BookMedical ,
  BookOpen ,
  BookReader ,
  Book ,
  BookmarkFull ,
  Bookmark ,
  Books ,
  Boombox ,
  BorderAlt ,
  BorderBottom ,
  BorderClear ,
  BorderHorizontal ,
  BorderInner ,
  BorderLeft ,
  BorderOut ,
  BorderRight ,
  BorderTop ,
  BorderVertical ,
  BowlingBall ,
  Box ,
  BracketsCurly ,
  Brain ,
  BriefcaseAlt ,
  Briefcase ,
  Bright ,
  BrightnessEmpty ,
  BrightnessHalf ,
  BrightnessLow ,
  BrightnessMinus ,
  BrightnessPlus ,
  Brightness ,
  BringBottom ,
  BringFront ,
  Browser ,
  BrushAlt ,
  Bug ,
  Building ,
  Bullseye ,
  BusAlt ,
  BusSchool ,
  Bus ,
  CalculatorAlt ,
  Calculator ,
  CalendarAlt ,
  CalendarSlash ,
  Calender ,
  Calling ,
  CameraChange ,
  CameraPlus ,
  CameraSlash ,
  Camera ,
  Cancel ,
  Capsule ,
  Capture ,
  CarSideview ,
  CarSlash ,
  CarWash ,
  Car ,
  CardAtm ,
  CaretRight ,
  Cell ,
  Celsius ,
  ChannelAdd ,
  Channel ,
  ChartBarAlt ,
  ChartBar ,
  ChartDown ,
  ChartGrowthAlt ,
  ChartGrowth ,
  ChartLine ,
  ChartPieAlt ,
  ChartPie ,
  Chart ,
  ChatBubbleUser ,
  ChatInfo ,
  Chat ,
  CheckCircle ,
  CheckSquare ,
  Check ,
  CircleLayer ,
  Circle ,
  Circuit ,
  ClapperBoard ,
  ClinicMedical ,
  ClipboardAlt ,
  ClipboardBlank ,
  ClipboardNotes ,
  Clipboard ,
  ClockEight ,
  ClockFive ,
  ClockNine ,
  ClockSeven ,
  ClockTen ,
  ClockThree ,
  ClockTwo ,
  Clock ,
  ClosedCaptioningSlash ,
  ClosedCaptioning ,
  CloudBlock ,
  CloudBookmark ,
  CloudCheck ,
  CloudComputing ,
  CloudDataConnection ,
  CloudDatabaseTree ,
  CloudDownload ,
  CloudDrizzle ,
  CloudExclamation ,
  CloudHail ,
  CloudHeart ,
  CloudInfo ,
  CloudLock ,
  CloudMeatball ,
  CloudMoonHail ,
  CloudMoonMeatball ,
  CloudMoonRain ,
  CloudMoonShowers ,
  CloudMoon ,
  CloudQuestion ,
  CloudRainSun ,
  CloudRain ,
  CloudRedo ,
  CloudShare ,
  CloudShield ,
  CloudShowersAlt ,
  CloudShowersHeavy ,
  CloudShowers ,
  CloudSlash ,
  CloudSunHail ,
  CloudSunMeatball ,
  CloudSunRainAlt ,
  CloudSunRain ,
  CloudSunTear ,
  CloudSun ,
  CloudTimes ,
  CloudUnlock ,
  CloudUpload ,
  CloudWifi ,
  CloudWind ,
  Cloud ,
  Clouds ,
  Club ,
  CodeBranch ,
  Coffee ,
  Cog ,
  Coins ,
  Columns ,
  CommentAdd ,
  CommentAltBlock ,
  CommentAltChartLines ,
  CommentAltCheck ,
  CommentAltDots ,
  CommentAltDownload ,
  CommentAltEdit ,
  CommentAltExclamation ,
  CommentAltHeart ,
  CommentAltImage ,
  CommentAltInfo ,
  CommentAltLines ,
  CommentAltLock ,
  CommentAltMedical ,
  CommentAltMessage ,
  CommentAltNotes ,
  CommentAltPlus ,
  CommentAltQuestion ,
  CommentAltRedo ,
  CommentAltSearch ,
  CommentAltShare ,
  CommentAltShield ,
  CommentAltSlash ,
  CommentAltUpload ,
  CommentAltVerify ,
  CommentAlt ,
  CommentBlock ,
  CommentChartLine ,
  CommentCheck ,
  CommentDots ,
  CommentDownload ,
  CommentEdit ,
  CommentExclamation ,
  CommentHeart ,
  CommentImage ,
  CommentInfoAlt ,
  CommentInfo ,
  CommentLines ,
  CommentLock ,
  CommentMedical ,
  CommentMessage ,
  CommentNotes ,
  CommentPlus ,
  CommentQuestion ,
  CommentRedo ,
  CommentSearch ,
  CommentShare ,
  CommentShield ,
  CommentSlash ,
  CommentUpload ,
  CommentVerify ,
  $$Comment ,
  CommentsAlt ,
  Comments ,
  CompactDisc ,
  Comparison ,
  Compass ,
  CompressAltLeft ,
  CompressAlt ,
  CompressArrows ,
  CompressLines ,
  CompressPoint ,
  CompressV ,
  Compress ,
  Confused ,
  Constructor ,
  CopyAlt ,
  CopyLandscape ,
  Copy ,
  Copyright ,
  CornerDownLeft ,
  CornerDownRightAlt ,
  CornerDownRight ,
  CornerLeftDown ,
  CornerRightDown ,
  CornerUpLeftAlt ,
  CornerUpLeft ,
  CornerUpRightAlt ,
  CornerUpRight ,
  Coronavirus ,
  CreateDashboard ,
  CreativeCommonsPd ,
  CreditCardSearch ,
  CreditCard ,
  Crockery ,
  CropAltRotateLeft ,
  CropAltRotateRight ,
  CropAlt ,
  CrosshairAlt ,
  Crosshair ,
  Crosshairs ,
  Css3Simple ,
  Cube ,
  Dashboard ,
  DataSharing ,
  DatabaseAlt ,
  Database ,
  Desert ,
  DesktopAltSlash ,
  DesktopAlt ,
  DesktopCloudAlt ,
  DesktopSlash ,
  Desktop ,
  DialpadAlt ,
  Dialpad ,
  Diamond ,
  DiaryAlt ,
  Diary ,
  DiceFive ,
  DiceFour ,
  DiceOne ,
  DiceSix ,
  DiceThree ,
  DiceTwo ,
  Direction ,
  Directions ,
  Discord ,
  DizzyMeh ,
  Dna ,
  Docker ,
  DocumentInfo ,
  DocumentLayoutCenter ,
  DocumentLayoutLeft ,
  DocumentLayoutRight ,
  DollarAlt ,
  DollarSignAlt ,
  DollarSign ,
  DownloadAlt ,
  Draggabledots ,
  Dribbble ,
  Drill ,
  Dropbox ,
  Dumbbell ,
  Ear ,
  EditAlt ,
  Edit ,
  ElipsisDoubleVAlt ,
  EllipsisH ,
  EllipsisV ,
  Emoji ,
  EnglishToChinese ,
  Enter ,
  EnvelopeAdd ,
  EnvelopeAlt ,
  EnvelopeBlock ,
  EnvelopeBookmark ,
  EnvelopeCheck ,
  EnvelopeDownloadAlt ,
  EnvelopeDownload ,
  EnvelopeEdit ,
  EnvelopeExclamation ,
  EnvelopeHeart ,
  EnvelopeInfo ,
  EnvelopeLock ,
  EnvelopeMinus ,
  EnvelopeOpen ,
  EnvelopeQuestion ,
  EnvelopeReceive ,
  EnvelopeRedo ,
  EnvelopeSearch ,
  EnvelopeSend ,
  EnvelopeShare ,
  EnvelopeShield ,
  EnvelopeStar ,
  EnvelopeTimes ,
  EnvelopeUploadAlt ,
  EnvelopeUpload ,
  Envelope ,
  Envelopes ,
  EqualCircle ,
  Estate ,
  EuroCircle ,
  Euro ,
  ExchangeAlt ,
  Exchange ,
  ExclamationCircle ,
  ExclamationOctagon ,
  ExclamationTriangle ,
  Exclamation ,
  Exclude ,
  ExpandAlt ,
  ExpandArrowsAlt ,
  ExpandArrows ,
  ExpandFromCorner ,
  ExpandLeft ,
  ExpandRight ,
  Export ,
  ExposureAlt ,
  ExposureIncrease ,
  ExternalLinkAlt ,
  EyeSlash ,
  Eye ,
  FacebookF ,
  FacebookMessengerAlt ,
  FacebookMessenger ,
  Facebook ,
  Fahrenheit ,
  FastMailAlt ,
  FastMail ,
  Favorite ,
  Feedback ,
  FidgetSpinner ,
  FileAlt ,
  FileBlank ,
  FileBlockAlt ,
  FileBookmarkAlt ,
  FileCheckAlt ,
  FileCheck ,
  FileContractDollar ,
  FileContract ,
  FileCopyAlt ,
  FileDownloadAlt ,
  FileDownload ,
  FileEditAlt ,
  FileExclamationAlt ,
  FileExclamation ,
  FileExport ,
  FileGraph ,
  FileHeart ,
  FileImport ,
  FileInfoAlt ,
  FileLandscapeAlt ,
  FileLandscape ,
  FileLanscapeSlash ,
  FileLockAlt ,
  FileMedicalAlt ,
  FileMedical ,
  FileMinusAlt ,
  FileMinus ,
  FileNetwork ,
  FilePlusAlt ,
  FilePlus ,
  FileQuestionAlt ,
  FileQuestion ,
  FileRedoAlt ,
  FileSearchAlt ,
  FileShareAlt ,
  FileShieldAlt ,
  FileSlash ,
  FileTimesAlt ,
  FileTimes ,
  FileUploadAlt ,
  FileUpload ,
  $$File ,
  FilesLandscapesAlt ,
  FilesLandscapes ,
  Film ,
  FilterSlash ,
  Filter ,
  Fire ,
  FlaskPotion ,
  Flask ,
  FlipHAlt ,
  FlipH ,
  FlipVAlt ,
  FlipV ,
  Flower ,
  FocusAdd ,
  FocusTarget ,
  Focus ,
  FolderCheck ,
  FolderDownload ,
  FolderExclamation ,
  FolderHeart ,
  FolderInfo ,
  FolderLock ,
  FolderMedical ,
  FolderMinus ,
  FolderNetwork ,
  FolderOpen ,
  FolderPlus ,
  FolderQuestion ,
  FolderSlash ,
  FolderTimes ,
  FolderUpload ,
  Folder ,
  Font ,
  FootballAmerican ,
  FootballBall ,
  Football ,
  ForecastcloudMoonTear ,
  ForwadedCall ,
  Forward ,
  Frown ,
  GameStructure ,
  Gift ,
  GithubAlt ,
  Github ,
  Gitlab ,
  GlassMartiniAltSlash ,
  GlassMartiniAlt ,
  GlassMartini ,
  GlassTea ,
  Glass ,
  Globe ,
  Gold ,
  GolfBall ,
  GoogleDriveAlt ,
  GoogleDrive ,
  GoogleHangoutsAlt ,
  GoogleHangouts ,
  GooglePlay ,
  Google ,
  GraduationCap ,
  GraphBar ,
  Grid ,
  Grids ,
  GrinTongueWinkAlt ,
  GrinTongueWink ,
  Grin ,
  GripHorizontalLine ,
  HardHat ,
  Hdd ,
  HeadSideCough ,
  HeadSideMask ,
  HeadSide ,
  HeadphoneSlash ,
  HeadphonesAlt ,
  Headphones ,
  HeartAlt ,
  HeartBreak ,
  HeartMedical ,
  HeartRate ,
  HeartSign ,
  Heart ,
  Heartbeat ,
  HindiToChinese ,
  Hipchat ,
  HistoryAlt ,
  $$History ,
  Home ,
  HorizontalAlignCenter ,
  HorizontalAlignLeft ,
  HorizontalAlignRight ,
  HorizontalDistributionCenter ,
  HorizontalDistributionLeft ,
  HorizontalDistributionRight ,
  HospitalSquareSign ,
  HospitalSymbol ,
  Hospital ,
  Hourglass ,
  HouseUser ,
  Html3Alt ,
  Html3 ,
  Html5Alt ,
  Html5 ,
  Hunting ,
  Icons ,
  Illustration ,
  ImageAltSlash ,
  ImageBlock ,
  ImageBroken ,
  ImageCheck ,
  ImageDownload ,
  ImageEdit ,
  ImageLock ,
  ImageMinus ,
  ImagePlus ,
  ImageQuestion ,
  ImageRedo ,
  ImageResizeLandscape ,
  ImageResizeSquare ,
  ImageSearch ,
  ImageShare ,
  ImageShield ,
  ImageSlash ,
  ImageTimes ,
  ImageUpload ,
  ImageV ,
  $$Image ,
  Images ,
  Import ,
  Inbox ,
  IncomingCall ,
  InfoCircle ,
  Info ,
  InstagramAlt ,
  Instagram ,
  IntercomAlt ,
  Intercom ,
  Invoice ,
  Italic ,
  Jackhammer ,
  JavaScript ,
  Kayak ,
  KeySkeletonAlt ,
  KeySkeleton ,
  KeyboardAlt ,
  KeyboardHide ,
  KeyboardShow ,
  Keyboard ,
  KeyholeCircle ,
  KeyholeSquareFull ,
  KeyholeSquare ,
  Kid ,
  LabelAlt ,
  Label ,
  Lamp ,
  Language ,
  LaptopCloud ,
  LaptopConnection ,
  Laptop ,
  Laughing ,
  LayerGroupSlash ,
  LayerGroup ,
  LayersAlt ,
  LayersSlash ,
  Layers ,
  LeftArrowFromLeft ,
  LeftArrowToLeft ,
  LeftIndentAlt ,
  LeftIndent ,
  LeftToRightTextDirection ,
  LetterChineseA ,
  LetterEnglishA ,
  LetterHindiA ,
  LetterJapaneseA ,
  LifeRing ,
  LightbulbAlt ,
  Lightbulb ,
  LineAlt ,
  LineSpacing ,
  Line ,
  LinkAdd ,
  LinkAlt ,
  LinkBroken ,
  LinkH ,
  Link ,
  LinkedinAlt ,
  Linkedin ,
  Linux ,
  LiraSign ,
  ListOlAlt ,
  ListOl ,
  ListUiAlt ,
  ListUl ,
  LocationArrowAlt ,
  LocationArrow ,
  LocationPinAlt ,
  LocationPoint ,
  LockAccess ,
  LockAlt ,
  LockOpenAlt ,
  LockSlash ,
  Lock ,
  LottiefilesAlt ,
  Lottiefiles ,
  LuggageCart ,
  MailboxAlt ,
  Mailbox ,
  MapMarkerAlt ,
  MapMarkerEdit ,
  MapMarkerInfo ,
  MapMarkerMinus ,
  MapMarkerPlus ,
  MapMarkerQuestion ,
  MapMarkerShield ,
  MapMarkerSlash ,
  MapMarker ,
  MapPinAlt ,
  MapPin ,
  $$Map ,
  Mars ,
  MasterCard ,
  MaximizeLeft ,
  Medal ,
  MedicalDrip ,
  MedicalSquareFull ,
  MedicalSquare ,
  MediumM ,
  Medkit ,
  MeetingBoard ,
  Megaphone ,
  MehAlt ,
  MehClosedEye ,
  Meh ,
  Message ,
  Metro ,
  MicrophoneSlash ,
  Microphone ,
  Microscope ,
  Microsoft ,
  MinusCircle ,
  MinusPath ,
  MinusSquareFull ,
  MinusSquare ,
  Minus ,
  MissedCall ,
  MobileAndroidAlt ,
  MobileAndroid ,
  MobileVibrate ,
  Modem ,
  MoneyBillSlash ,
  MoneyBillStack ,
  MoneyBill ,
  MoneyInsert ,
  MoneyStack ,
  MoneyWithdraw ,
  MoneyWithdrawal ,
  MoneybagAlt ,
  Moneybag ,
  MonitorHeartRate ,
  Monitor ,
  MoonEclipse ,
  Moon ,
  Moonset ,
  MountainsSun ,
  Mountains ,
  MouseAlt2 ,
  MouseAlt ,
  Mouse ,
  Multiply ,
  MusicNote ,
  MusicTuneSlash ,
  Music ,
  NA ,
  $$Navigator ,
  Nerd ,
  Newspaper ,
  Ninja ,
  NoEntry ,
  Notebooks ,
  Notes ,
  ObjectGroup ,
  ObjectUngroup ,
  Octagon ,
  Okta ,
  OperaAlt ,
  Opera ,
  OutgoingCall ,
  Package ,
  Padlock ,
  Pagelines ,
  Pagerduty ,
  PaintTool ,
  Palette ,
  PanelAdd ,
  PanoramaHAlt ,
  PanoramaH ,
  PanoramaV ,
  Paperclip ,
  Paragraph ,
  Parcel ,
  ParkingCircle ,
  ParkingSquare ,
  PathfinderUnite ,
  Pathfinder ,
  PauseCircle ,
  Pause ,
  Paypal ,
  Pen ,
  Pentagon ,
  Percentage ,
  PhoneAlt ,
  PhonePause ,
  PhoneSlash ,
  PhoneTimes ,
  PhoneVolume ,
  Phone ,
  Picture ,
  PizzaSlice ,
  PlaneArrival ,
  PlaneDeparture ,
  PlaneFly ,
  Plane ,
  PlayCircle ,
  Play ,
  Plug ,
  PlusCircle ,
  PlusSquare ,
  Plus ,
  Podium ,
  Polygon ,
  PostStamp ,
  Postcard ,
  PoundCircle ,
  Pound ,
  Power ,
  PrescriptionBottle ,
  PresentationCheck ,
  PresentationEdit ,
  PresentationLine ,
  PresentationLinesAlt ,
  PresentationMinus ,
  PresentationPlay ,
  PresentationPlus ,
  PresentationTimes ,
  Presentation ,
  Previous ,
  PricetagAlt ,
  PrintSlash ,
  Print ,
  Process ,
  Processor ,
  ProgrammingLanguage ,
  Pump ,
  PuzzlePiece ,
  QrcodeScan ,
  QuestionCircle ,
  Question ,
  Rainbow ,
  RaindropsAlt ,
  Raindrops ,
  ReceiptAlt ,
  Receipt ,
  RecordAudio ,
  RedditAlienAlt ,
  Redo ,
  Refresh ,
  Registered ,
  Repeat ,
  Restaurant ,
  RightIndentAlt ,
  RightToLeftTextDirection ,
  Robot ,
  Rocket ,
  RopeWay ,
  Rotate360 ,
  RssAlt ,
  RssInterface ,
  Rss ,
  RulerCombined ,
  Ruler ,
  RupeeSign ,
  SadCry ,
  SadCrying ,
  SadDizzy ,
  SadSquint ,
  Sad ,
  SanitizerAlt ,
  Sanitizer ,
  Save ,
  ScalingLeft ,
  ScalingRight ,
  Scenery ,
  Schedule ,
  Screw ,
  ScrollH ,
  Scroll ,
  SearchAlt ,
  SearchMinus ,
  SearchPlus ,
  Search ,
  Selfie ,
  ServerAlt ,
  ServerConnection ,
  ServerNetworkAlt ,
  ServerNetwork ,
  Server ,
  Servers ,
  Servicemark ,
  Setting ,
  ShareAlt ,
  Share ,
  ShieldCheck ,
  ShieldExclamation ,
  ShieldPlus ,
  ShieldQuestion ,
  ShieldSlash ,
  Shield ,
  Ship ,
  Shop ,
  ShoppingBag ,
  ShoppingBasket ,
  ShoppingCartAlt ,
  ShoppingCart ,
  Shovel ,
  Shrink ,
  Shuffle ,
  ShutterAlt ,
  Shutter ,
  Sick ,
  Sigma ,
  SignAlt ,
  SignInAlt ,
  SignLeft ,
  SignOutAlt ,
  SignRight ,
  SignalAlt3 ,
  SignalAlt ,
  Signal ,
  Signin ,
  Signout ,
  Silence ,
  SilentSquint ,
  SimCard ,
  Sitemap ,
  SkipForwardAlt ,
  SkipForwardCircle ,
  SkipForward ,
  SkypeAlt ,
  Skype ,
  SlackAlt ,
  Slack ,
  SliderHRange ,
  SliderH ,
  SlidersVAlt ,
  SlidersV ,
  SmileBeam ,
  SmileDizzy ,
  SmileSquintWinkAlt ,
  SmileSquintWink ,
  SmileWinkAlt ,
  SmileWink ,
  Smile ,
  SnapchatAlt ,
  SnapchatGhost ,
  SnapchatSquare ,
  SnowFlake ,
  SnowflakeAlt ,
  Snowflake ,
  SocialDistancing ,
  SortAmountDown ,
  SortAmountUp ,
  Sort ,
  Sorting ,
  SpaceKey ,
  Spade ,
  Sperms ,
  Spin ,
  SpinnerAlt ,
  Spinner ,
  SquareFull ,
  SquareShape ,
  Square ,
  Squint ,
  StarHalfAlt ,
  Star ,
  StepBackwardAlt ,
  StepBackwardCircle ,
  StepBackward ,
  StepForward ,
  StethoscopeAlt ,
  Stethoscope ,
  StopCircle ,
  StopwatchSlash ,
  Stopwatch ,
  StoreAlt ,
  StoreSlash ,
  Store ,
  Streering ,
  Stretcher ,
  Subject ,
  SubwayAlt ,
  Subway ,
  SuitcaseAlt ,
  Suitcase ,
  Sun ,
  Sunset ,
  Surprise ,
  Swatchbook ,
  Swiggy ,
  Swimmer ,
  SyncExclamation ,
  SyncSlash ,
  Sync ,
  Syringe ,
  TableTennis ,
  Table ,
  Tablet ,
  Tablets ,
  TachometerFastAlt ,
  TachometerFast ,
  TagAlt ,
  Tag ,
  Tape ,
  Taxi ,
  Tear ,
  TelegramAlt ,
  Telegram ,
  Telescope ,
  TemperatureEmpty ,
  TemperatureHalf ,
  TemperatureMinus ,
  TemperaturePlus ,
  TemperatureQuarter ,
  TemperatureThreeQuarter ,
  Temperature ,
  TennisBall ,
  TextFields ,
  TextSize ,
  TextStrikeThrough ,
  $$Text ,
  ThLarge ,
  ThSlash ,
  Th ,
  Thermometer ,
  ThumbsDown ,
  ThumbsUp ,
  ThunderstormMoon ,
  ThunderstormSun ,
  Thunderstorm ,
  Ticket ,
  TimesCircle ,
  TimesSquare ,
  Times ,
  ToggleOff ,
  ToggleOn ,
  ToiletPaper ,
  TopArrowFromTop ,
  TopArrowToTop ,
  Tornado ,
  TrademarkCircle ,
  Trademark ,
  TrafficBarrier ,
  TrafficLight ,
  Transaction ,
  TrashAlt ,
  Trash ,
  Trees ,
  Triangle ,
  Trophy ,
  Trowel ,
  TruckLoading ,
  Truck ,
  TumblrAlt ,
  TumblrSquare ,
  Tumblr ,
  TvRetroSlash ,
  TvRetro ,
  TwitterAlt ,
  Twitter ,
  Umbrella ,
  Unamused ,
  Underline ,
  University ,
  UnlockAlt ,
  Unlock ,
  UploadAlt ,
  Upload ,
  UsdCircle ,
  UsdSquare ,
  UserArrows ,
  UserCheck ,
  UserCircle ,
  UserExclamation ,
  UserLocation ,
  UserMd ,
  UserMinus ,
  UserNurse ,
  UserPlus ,
  UserSquare ,
  UserTimes ,
  User ,
  UsersAlt ,
  UtensilsAlt ,
  Utensils ,
  VectorSquareAlt ,
  VectorSquare ,
  Venus ,
  VerticalAlignBottom ,
  VerticalAlignCenter ,
  VerticalAlignTop ,
  VerticalDistributeBottom ,
  VerticalDistributionCenter ,
  VerticalDistributionTop ,
  VideoQuestion ,
  VideoSlash ,
  Video ,
  VirusSlash ,
  VisualStudio ,
  VkAlt ,
  Vk ,
  VoicemailRectangle ,
  Voicemail ,
  Volleyball ,
  VolumeDown ,
  VolumeMute ,
  VolumeOff ,
  VolumeUp ,
  Volume ,
  VuejsAlt ,
  Vuejs ,
  Wall ,
  Wallet ,
  WatchAlt ,
  Watch ,
  WaterDropSlash ,
  WaterGlass ,
  Water ,
  WebGridAlt ,
  WebGrid ,
  WebSectionAlt ,
  WebSection ,
  Webcam ,
  Weight ,
  WhatsappAlt ,
  Whatsapp ,
  WheelBarrow ,
  WheelchairAlt ,
  Wheelchair ,
  WifiRouter ,
  WifiSlash ,
  Wifi ,
  WindMoon ,
  WindSun ,
  Wind ,
  WindowGrid ,
  WindowMaximize ,
  WindowSection ,
  $$Window ,
  Windows ,
  Windsock ,
  Windy ,
  WordpressSimple ,
  Wordpress ,
  WrapText ,
  Wrench ,
  XAdd ,
  X ,
  YenCircle ,
  Yen ,
  YinYang ,
  Youtube ,
}
/* No side effect */
