// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilUsdSquare from "@iconscout/react-unicons/icons/uil-usd-square";

var Impl = {};

function UsdSquare(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilUsdSquare, tmp);
}

var make = UsdSquare;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
