// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilUserTimes from "@iconscout/react-unicons/icons/uil-user-times";

var Impl = {};

function UserTimes(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilUserTimes, tmp);
}

var make = React.memo(UserTimes);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
