// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilVerticalDistributionCenter from "@iconscout/react-unicons/icons/uil-vertical-distribution-center";

var Impl = {};

function VerticalDistributionCenter(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilVerticalDistributionCenter, tmp);
}

var make = React.memo(VerticalDistributionCenter);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
