// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilVerticalAlignTop from "@iconscout/react-unicons/icons/uil-vertical-align-top";

var Impl = {};

function VerticalAlignTop(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilVerticalAlignTop, tmp);
}

var make = React.memo(VerticalAlignTop);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
