// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilVerticalDistributeBottom from "@iconscout/react-unicons/icons/uil-vertical-distribute-bottom";

var Impl = {};

function VerticalDistributeBottom(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilVerticalDistributeBottom, tmp);
}

var make = React.memo(VerticalDistributeBottom);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
