// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilVerticalAlignCenter from "@iconscout/react-unicons/icons/uil-vertical-align-center";

var Impl = {};

function VerticalAlignCenter(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilVerticalAlignCenter, tmp);
}

var make = React.memo(VerticalAlignCenter);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
