// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilVirusSlash from "@iconscout/react-unicons/icons/uil-virus-slash";

var Impl = {};

function VirusSlash(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilVirusSlash, tmp);
}

var make = React.memo(VirusSlash);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
