// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilVolumeUp from "@iconscout/react-unicons/icons/uil-volume-up";

var Impl = {};

function VolumeUp(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilVolumeUp, tmp);
}

var make = VolumeUp;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
