// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilWaterGlass from "@iconscout/react-unicons/icons/uil-water-glass";

var Impl = {};

function WaterGlass(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilWaterGlass, tmp);
}

var make = WaterGlass;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
