// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilWebGrid from "@iconscout/react-unicons/icons/uil-web-grid";

var Impl = {};

function WebGrid(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilWebGrid, tmp);
}

var make = WebGrid;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
