// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilWebGridAlt from "@iconscout/react-unicons/icons/uil-web-grid-alt";

var Impl = {};

function WebGridAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilWebGridAlt, tmp);
}

var make = React.memo(WebGridAlt);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
