// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilWhatsappAlt from "@iconscout/react-unicons/icons/uil-whatsapp-alt";

var Impl = {};

function WhatsappAlt(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilWhatsappAlt, tmp);
}

var make = WhatsappAlt;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
