// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilWifiSlash from "@iconscout/react-unicons/icons/uil-wifi-slash";

var Impl = {};

function WifiSlash(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilWifiSlash, tmp);
}

var make = WifiSlash;

export {
  Impl ,
  make ,
  
}
/* react Not a pure module */
