// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilWindow from "@iconscout/react-unicons/icons/uil-window";

var Impl = {};

function $$Window(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilWindow, tmp);
}

var make = React.memo($$Window);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
