// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilWindSun from "@iconscout/react-unicons/icons/uil-wind-sun";

var Impl = {};

function WindSun(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilWindSun, tmp);
}

var make = React.memo(WindSun);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
