// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import UilWindowGrid from "@iconscout/react-unicons/icons/uil-window-grid";

var Impl = {};

function WindowGrid(Props) {
  var className = Props.className;
  var size = Props.size;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = className;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return React.createElement(UilWindowGrid, tmp);
}

var make = React.memo(WindowGrid);

export {
  Impl ,
  make ,
  
}
/* make Not a pure module */
